registryMirrorSecret:
  endpoint: "{{.mirrorEndpoint}}"
  username: "{{.mirrorUsername}}"
  password: "{{.mirrorPassword}}"
  cacertcontent: "{{.mirrorCACertContent}}"
  insecure: "{{.insecureSkipVerify}}"
awsSecret:
  id: "{{.eksaAccessKeyId}}"
  secret: "{{.eksaSecretAccessKey}}"
  region: "{{.eksaRegion}}"
  config: "{{.eksaAwsConfig}}"