# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
# GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "weekly"
  labels:
    - "dependabot"
    - "ok-to-test"
# Main Go module and release module
# grouped together since frequently updates
# in main cascade down to the release module.
- package-ecosystem: "gomod"
  directories:
  - "/"
  - "/release/cli"
  schedule:
    interval: "weekly"
    day: "monday"
  ## group all dependencies in one PR to avoid churn.
  groups:
    all-go-mod-patch-and-minor:
      patterns: [ "*" ]
      update-types: [ "patch", "minor" ]
  ignore:
  # Ignore controller-runtime as its upgraded manually.
  - dependency-name: "sigs.k8s.io/controller-runtime"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
    # Ignore k8s and its transitives modules as they are upgraded manually together with controller-runtime.
  - dependency-name: "k8s.io/*"
    update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  labels:
    - "dependabot"
    - "ok-to-test"
