version: "2"
linters:
  enable:
    - gocyclo
    - godot
    - nakedret
    - revive
    - staticcheck
  settings:
    gocyclo:
      min-complexity: 10
    godot:
      exclude:
        - (?i)^\s*todo
      period: true
    staticcheck:
      checks: ["-SA1019"]
    revive:
      rules:
        - name: dot-imports
          arguments:
            - allowedPackages:
              - github.com/onsi/gomega
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    paths:
      - zz_generated.*\.go$
      - .*/mocks
      - manager/tilt_modules
      - internal/aws-sdk-go-v2
      - pkg/providers/snow/api/v1beta1
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/aws/eks-anywhere)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - zz_generated.*\.go$
      - .*/mocks
      - manager/tilt_modules
      - internal/aws-sdk-go-v2
      - pkg/providers/snow/api/v1beta1
      - third_party$
      - builtin$
      - examples$
