run:
  timeout: 5m
  skip-files:
  - "zz_generated.*\\.go$"
  skip-dirs:
  - ".*/mocks"
  - "manager/tilt_modules"
linters:
  enable:
    - gofumpt
    - gci
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/aws/eks-anywhere)
    custom-order: true
    skip-generated: false
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
