apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: vgg-cluster
spec:
  clusterNetwork:
    cni: cilium
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: ""
    machineGroupRef:
      kind: VSphereMachineConfig
      name: vgg-cluster-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: vgg-cluster
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: vgg-cluster-etcd
  kubernetesVersion: "1.21"
  managementCluster:
    name: vgg-cluster
  workerNodeGroupConfigurations:
  - count: 2
    machineGroupRef:
      kind: VSphereMachineConfig
      name: vgg-cluster

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: vgg-cluster
spec:
  datacenter: ""
  insecure: false
  network: ""
  server: ""
  thumbprint: ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: vgg-cluster-cp
spec:
  datastore: ""
  diskGiB: 25
  folder: ""
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: ""
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAA...

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: vgg-cluster
spec:
  datastore: ""
  diskGiB: 25
  folder: ""
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: ""
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAA...

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: vgg-cluster-etcd
spec:
  datastore: ""
  diskGiB: 25
  folder: ""
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: ""
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa AAAA...

---

