# -*- mode: Python -*-
settings = read_json('tilt-settings.json', default={})

load('ext://restart_process', 'docker_build_with_restart')
allow_k8s_contexts(settings.get("allowed_contexts"))
default_registry(settings.get('default_registry'))

IMG = 'cluster-controller:latest'
PROJECT_ROOT='./../'
CONTROLLERS_FOLDER = PROJECT_ROOT + 'controllers'
MANAGER_FOLDER = PROJECT_ROOT + 'manager'
MANAGER_BIN_FOLDER = MANAGER_FOLDER + '/bin'
API_FOLDER = PROJECT_ROOT + 'pkg/api'
CONFIG_FOLDER = PROJECT_ROOT + 'config'
KUSTOMIZE_TILT_FOLDER = CONFIG_FOLDER + '/tilt'
KUSTOMIZE_BIN = os.path.abspath(PROJECT_ROOT + 'hack/tools/bin/kustomize')
watch_settings(ignore=[KUSTOMIZE_TILT_FOLDER]) #ignore kustomize tilt folder to avoid infinite loop
FULL_LIFECYCLE_API_KEY = "FULL_LIFECYCLE_API"
FULL_LIFECYCLE_API_VALUE = os.getenv(FULL_LIFECYCLE_API_KEY, "false")

def yaml():
    local('cd ' + KUSTOMIZE_TILT_FOLDER + ' && ' + KUSTOMIZE_BIN + ' edit set image controller=' + IMG)
    return kustomize(KUSTOMIZE_TILT_FOLDER)

def binary():
    return 'CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -o ./bin/manager ' + MANAGER_FOLDER + '/main.go'

local_resource(
  'eksa-controller-compile',
  binary(),
  deps=[MANAGER_FOLDER, CONTROLLERS_FOLDER, API_FOLDER],
  ignore=[MANAGER_BIN_FOLDER, API_FOLDER + '/*/zz_generated.deepcopy.go'])

FULL_LIFECYCLE_API_ENV = FULL_LIFECYCLE_API_KEY + "=" + FULL_LIFECYCLE_API_VALUE

DOCKERFILE = '''FROM golang:alpine
WORKDIR /
ENV ''' + FULL_LIFECYCLE_API_ENV + '''
RUN apk --no-cache add curl
RUN curl -L -o - "https://github.com/vmware/govmomi/releases/latest/download/govc_$(uname -s)_$(uname -m).tar.gz" | tar -C /usr/local/bin -xvzf - govc
RUN curl -L -o - "https://get.helm.sh/helm-v3.8.1-linux-amd64.tar.gz" | tar -C /usr/local/bin -xvzf - linux-amd64/helm
RUN mv /usr/local/bin/linux-amd64/helm /usr/local/bin/
COPY ./bin/manager /
CMD ["/manager"]
'''

k8s_yaml(yaml())

docker_build_with_restart(
	IMG,
	'.', 
	dockerfile_contents=DOCKERFILE,
	entrypoint='/manager',
	only=['./bin/manager'],
	live_update=[
		sync('./bin/manager', '/manager'),
	]
)