apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: {{.Namespace}}
spec:
  template:
    spec:
      containers:
      - image: {{.SourceControllerImage}}
        name: manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: {{.Namespace}}
spec:
  template:
    spec:
      containers:
      - image: {{.KustomizeControllerImage}}
        name: manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: {{.Namespace}}
spec:
  template:
    spec:
      containers:
      - image: {{.HelmControllerImage}}
        name: manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller
  namespace: {{.Namespace}}
spec:
  template:
    spec:
      containers:
      - image: {{.NotificationControllerImage}}
        name: manager