providers:
  - name: "docker"
    url: "{{.dir}}/infrastructure-docker/v0.3.19/infrastructure-components-development.yaml"
    type: "InfrastructureProvider"
    version: "v0.3.19"
  - name: "vsphere"
    url: "{{.dir}}/infrastructure-vsphere/v0.7.8/infrastructure-components.yaml"
    type: "InfrastructureProvider"
    version: "v0.7.8"
  - name: "aws"
    url: "{{.dir}}/infrastructure-aws/v0.6.4/infrastructure-components.yaml"
    type: "InfrastructureProvider"
    version: "v0.6.4"
  - name: "cluster-api"
    url: "{{.dir}}/cluster-api/v0.3.19/core-components.yaml"
    type: "CoreProvider"
    version: "v0.3.19"
  - name: "kubeadm"
    url: "{{.dir}}/control-plane-kubeadm/v0.3.19/control-plane-components.yaml"
    type: "ControlPlaneProvider"
    version: "v0.3.19"
  - name: "kubeadm"
    url: "{{.dir}}/bootstrap-kubeadm/v0.3.19/bootstrap-components.yaml"
    type: "BootstrapProvider"
    version: "v0.3.19"
  - name: "etcdadm-bootstrap"
    url: "{{.dir}}/bootstrap-etcdadm-bootstrap/v0.1.0/bootstrap-components.yaml"
    type: "BootstrapProvider"
    version: "v0.1.0"
  - name: "etcdadm-controller"
    url: "{{.dir}}/bootstrap-etcdadm-controller/v0.1.0/bootstrap-components.yaml"
    type: "BootstrapProvider"
    version: "v0.1.0"

overridesFolder: {{.dir}}
images:
  cert-manager/cert-manager-cainjector:
    repository: {{ .CertManagerInjectorRepository }}
    tag: {{ .CertManagerInjectorTag }}
  cert-manager/cert-manager-controller:
    repository: {{ .CertManagerControllerRepository }}
    tag: {{ .CertManagerControllerTag }}
  cert-manager/cert-manager-webhook:
    repository: {{ .CertManagerWebhookRepository }}
    tag: {{ .CertManagerWebhookTag }}
  cluster-api/cluster-api-controller:
    repository: {{ .ClusterApiControllerRepository }}
    tag: {{ .ClusterApiControllerTag }}
  cluster-api/kube-rbac-proxy:
    repository: {{ .ClusterApiKubeRbacProxyRepository }}
    tag: {{ .ClusterApiKubeRbacProxyTag }} #org one is v0.4.1
  bootstrap-kubeadm/kubeadm-bootstrap-controller:
    repository: {{ .KubeadmBootstrapControllerRepository }}
    tag: {{ .KubeadmBootstrapControllerTag }}
  bootstrap-kubeadm/kube-rbac-proxy:
    repository: {{ .KubeadmBootstrapKubeRbacProxyRepository }}
    tag: {{ .KubeadmBootstrapKubeRbacProxyTag }} #org one is v0.4.1
  control-plane-kubeadm/kubeadm-control-plane-controller:
    repository: {{ .KubeadmControlPlaneControllerRepository }}
    tag: {{ .KubeadmControlPlaneControllerTag }}
  control-plane-kubeadm/kube-rbac-proxy:
    repository: {{ .KubeadmControlPlaneKubeRbacProxyRepository }}
    tag: {{ .KubeadmControlPlaneKubeRbacProxyTag }} #org one is v0.4.1
  infrastructure-aws/cluster-api-aws-controller:
    repository: {{ .ClusterApiAwsControllerRepository }}
    tag: {{ .ClusterApiAwsControllerTag }}
  infrastructure-aws/kube-rbac-proxy:
    repository: {{ .ClusterApiAwsKubeRbacProxyRepository }}
    tag: {{ .ClusterApiAwsKubeRbacProxyTag }} #org one is v0.4.1
  infrastructure-vsphere/manager:
    repository: {{ .ClusterApiVSphereControllerRepository }}
    tag: {{ .ClusterApiVSphereControllerTag }}
  infrastructure-vsphere/kube-rbac-proxy:
    repository: {{ .ClusterApiVSphereKubeRbacProxyRepository }}
    tag: {{ .ClusterApiVSphereKubeRbacProxyTag }} #org one is v0.8.0
  infrastructure-docker/capd-manager:
    repository: {{.DockerManagerRepository}}
    tag: {{.DockerManagerTag}}
  infrastructure-docker/kube-rbac-proxy:
    repository: {{ .DockerKubeRbacProxyRepository }}
    tag: {{ .DockerKubeRbacProxyTag }} #org one is v0.4.0
  bootstrap-etcdadm-bootstrap/etcdadm-bootstrap-provider:
    repository: {{ .EtcdadmBootstrapProviderRepository }}
    tag: {{ .EtcdadmBootstrapProviderTag }}
  bootstrap-etcdadm-bootstrap/kube-rbac-proxy:
    repository: {{ .EtcdadmBootstrapProviderKubeRbacProxyRepository }}
    tag: {{ .EtcdadmBootstrapProviderKubeRbacProxyTag }} #org one is v0.4.0
  bootstrap-etcdadm-controller/etcdadm-controller:
    repository: {{ .EtcdadmControllerRepository }}
    tag: {{ .EtcdadmControllerTag }}
  bootstrap-etcdadm-controller/kube-rbac-proxy:
    repository: {{ .EtcdadmControllerKubeRbacProxyRepository }}
    tag: {{ .EtcdadmControllerKubeRbacProxyTag }} #org one is v0.4.0
cert-manager:
  timeout: 30m