providers:
  - name: "docker"
    url: "{{.dir}}/infrastructure-docker/{{.DockerProviderVersion}}/infrastructure-components-development.yaml"
    type: "InfrastructureProvider"
    version: "{{.DockerProviderVersion}}"
  - name: "tinkerbell"
    url: "{{.dir}}/infrastructure-tinkerbell/{{.TinkerbellProviderVersion}}/infrastructure-components.yaml"
    type: "InfrastructureProvider"
    version: "{{.TinkerbellProviderVersion}}"
  - name: "cloudstack"
    url: "{{.dir}}/infrastructure-cloudstack/{{.CloudStackProviderVersion}}/infrastructure-components.yaml"
    type: "InfrastructureProvider"
    version: "{{.CloudStackProviderVersion}}"
  - name: "vsphere"
    url: "{{.dir}}/infrastructure-vsphere/{{.VSphereProviderVersion}}/infrastructure-components.yaml"
    type: "InfrastructureProvider"
    version: "{{.VSphereProviderVersion}}"
  - name: "snow"
    url: "{{.dir}}/infrastructure-snow/{{.SnowProviderVersion}}/infrastructure-components.yaml"
    type: "InfrastructureProvider"
    version: "{{.SnowProviderVersion}}"
  - name: "cluster-api"
    url: "{{.dir}}/cluster-api/{{.ClusterApiProviderVersion}}/core-components.yaml"
    type: "CoreProvider"
    version: "{{.ClusterApiProviderVersion}}"
  - name: "kubeadm"
    url: "{{.dir}}/control-plane-kubeadm/{{.KubeadmControlPlaneProviderVersion}}/control-plane-components.yaml"
    type: "ControlPlaneProvider"
    version: "{{.KubeadmControlPlaneProviderVersion}}"
  - name: "kubeadm"
    url: "{{.dir}}/bootstrap-kubeadm/{{.KubeadmBootstrapProviderVersion}}/bootstrap-components.yaml"
    type: "BootstrapProvider"
    version: "{{.KubeadmBootstrapProviderVersion}}"
  - name: "etcdadm-bootstrap"
    url: "{{.dir}}/bootstrap-etcdadm-bootstrap/{{.EtcdadmBootstrapProviderVersion}}/bootstrap-components.yaml"
    type: "BootstrapProvider"
    version: "{{.EtcdadmBootstrapProviderVersion}}"
  - name: "etcdadm-controller"
    url: "{{.dir}}/bootstrap-etcdadm-controller/{{.EtcdadmControllerProviderVersion}}/bootstrap-components.yaml"
    type: "BootstrapProvider"
    version: "{{.EtcdadmControllerProviderVersion}}"
  - name: "nutanix"
    url: "{{.dir}}/infrastructure-nutanix/{{.NutanixProviderVersion}}/infrastructure-components.yaml"
    type: "InfrastructureProvider"
    version: "{{.NutanixProviderVersion}}"

overridesFolder: {{.dir}}
images:
  cert-manager/cert-manager-cainjector:
    repository: {{ .CertManagerInjectorRepository }}
    tag: {{ .CertManagerInjectorTag }}
  cert-manager/cert-manager-controller:
    repository: {{ .CertManagerControllerRepository }}
    tag: {{ .CertManagerControllerTag }}
  cert-manager/cert-manager-webhook:
    repository: {{ .CertManagerWebhookRepository }}
    tag: {{ .CertManagerWebhookTag }}
  cluster-api/cluster-api-controller:
    repository: {{ .ClusterApiControllerRepository }}
    tag: {{ .ClusterApiControllerTag }}
  cluster-api/kube-rbac-proxy:
    repository: {{ .ClusterApiKubeRbacProxyRepository }}
    tag: {{ .ClusterApiKubeRbacProxyTag }} #org one is v0.4.1
  bootstrap-kubeadm/kubeadm-bootstrap-controller:
    repository: {{ .KubeadmBootstrapControllerRepository }}
    tag: {{ .KubeadmBootstrapControllerTag }}
  bootstrap-kubeadm/kube-rbac-proxy:
    repository: {{ .KubeadmBootstrapKubeRbacProxyRepository }}
    tag: {{ .KubeadmBootstrapKubeRbacProxyTag }} #org one is v0.4.1
  control-plane-kubeadm/kubeadm-control-plane-controller:
    repository: {{ .KubeadmControlPlaneControllerRepository }}
    tag: {{ .KubeadmControlPlaneControllerTag }}
  control-plane-kubeadm/kube-rbac-proxy:
    repository: {{ .KubeadmControlPlaneKubeRbacProxyRepository }}
    tag: {{ .KubeadmControlPlaneKubeRbacProxyTag }} #org one is v0.4.1
  infrastructure-cloudstack/kube-rbac-proxy:
    repository: {{ .ClusterApiCloudStackKubeRbacProxyRepository }}
    tag: {{ .ClusterApiCloudStackKubeRbacProxyTag }} #org one is v0.8.0
  infrastructure-vsphere/manager:
    repository: {{ .ClusterApiVSphereControllerRepository }}
    tag: {{ .ClusterApiVSphereControllerTag }}
  infrastructure-vsphere/kube-rbac-proxy:
    repository: {{ .ClusterApiVSphereKubeRbacProxyRepository }}
    tag: {{ .ClusterApiVSphereKubeRbacProxyTag }} #org one is v0.8.0
  infrastructure-docker/capd-manager:
    repository: {{.DockerManagerRepository}}
    tag: {{.DockerManagerTag}}
  infrastructure-docker/kube-rbac-proxy:
    repository: {{ .DockerKubeRbacProxyRepository }}
    tag: {{ .DockerKubeRbacProxyTag }} #org one is v0.4.0
  infrastructure-nutanix/manager:
    repository: {{ .ClusterApiNutanixControllerRepository }}
    tag: {{ .ClusterApiNutanixControllerTag }}
  bootstrap-etcdadm-bootstrap/etcdadm-bootstrap-provider:
    repository: {{ .EtcdadmBootstrapProviderRepository }}
    tag: {{ .EtcdadmBootstrapProviderTag }}
  bootstrap-etcdadm-bootstrap/kube-rbac-proxy:
    repository: {{ .EtcdadmBootstrapProviderKubeRbacProxyRepository }}
    tag: {{ .EtcdadmBootstrapProviderKubeRbacProxyTag }} #org one is v0.4.0
  bootstrap-etcdadm-controller/etcdadm-controller:
    repository: {{ .EtcdadmControllerRepository }}
    tag: {{ .EtcdadmControllerTag }}
  bootstrap-etcdadm-controller/kube-rbac-proxy:
    repository: {{ .EtcdadmControllerKubeRbacProxyRepository }}
    tag: {{ .EtcdadmControllerKubeRbacProxyTag }} #org one is v0.4.0
cert-manager:
  timeout: 30m
  url: "{{.dir}}/cert-manager/{{.CertManagerVersion}}/cert-manager.yaml"
  version: {{.CertManagerVersion}}