providers:
  - name: "docker"
    url: "{{.dir}}/infrastructure-docker/{{.DockerProviderVersion}}/infrastructure-components-development.yaml"
    type: "InfrastructureProvider"
    version: "{{.DockerProviderVersion}}"
    {{- if (eq .IsActiveTinkerbellProvider "true") }}
  - name: "tinkerbell"
    url: "{{.dir}}/infrastructure-tinkerbell/{{.TinkerbellProviderVersion}}/infrastructure-components.yaml"
    type: "InfrastructureProvider"
    version: "{{.TinkerbellProviderVersion}}"
    {{- end }}
  - name: "cloudstack"
    url: "{{.dir}}/infrastructure-cloudstack/{{.CloudStackProviderVersion}}/infrastructure-components.yaml"
    type: "InfrastructureProvider"
    version: "{{.CloudStackProviderVersion}}"
  - name: "vsphere"
    url: "{{.dir}}/infrastructure-vsphere/{{.VSphereProviderVersion}}/infrastructure-components.yaml"
    type: "InfrastructureProvider"
    version: "{{.VSphereProviderVersion}}"
  - name: "aws"
    url: "{{.dir}}/infrastructure-aws/{{.AwsProviderVersion}}/infrastructure-components.yaml"
    type: "InfrastructureProvider"
    version: "{{.AwsProviderVersion}}"
  - name: "snow"
    url: "{{.dir}}/infrastructure-snow/{{.SnowProviderVersion}}/infrastructure-components.yaml"
    type: "InfrastructureProvider"
    version: "{{.SnowProviderVersion}}"
  - name: "cluster-api"
    url: "{{.dir}}/cluster-api/{{.ClusterApiProviderVersion}}/core-components.yaml"
    type: "CoreProvider"
    version: "{{.ClusterApiProviderVersion}}"
  - name: "kubeadm"
    url: "{{.dir}}/control-plane-kubeadm/{{.KubeadmControlPlaneProviderVersion}}/control-plane-components.yaml"
    type: "ControlPlaneProvider"
    version: "{{.KubeadmControlPlaneProviderVersion}}"
  - name: "kubeadm"
    url: "{{.dir}}/bootstrap-kubeadm/{{.KubeadmBootstrapProviderVersion}}/bootstrap-components.yaml"
    type: "BootstrapProvider"
    version: "{{.KubeadmBootstrapProviderVersion}}"
  - name: "etcdadm-bootstrap"
    url: "{{.dir}}/bootstrap-etcdadm-bootstrap/{{.EtcdadmBootstrapProviderVersion}}/bootstrap-components.yaml"
    type: "BootstrapProvider"
    version: "{{.EtcdadmBootstrapProviderVersion}}"
  - name: "etcdadm-controller"
    url: "{{.dir}}/bootstrap-etcdadm-controller/{{.EtcdadmControllerProviderVersion}}/bootstrap-components.yaml"
    type: "BootstrapProvider"
    version: "{{.EtcdadmControllerProviderVersion}}"

overridesFolder: {{.dir}}
images:
  cert-manager/cert-manager-cainjector:
    repository: {{ .CertManagerInjectorRepository }}
    tag: {{ .CertManagerInjectorTag }}
  cert-manager/cert-manager-controller:
    repository: {{ .CertManagerControllerRepository }}
    tag: {{ .CertManagerControllerTag }}
  cert-manager/cert-manager-webhook:
    repository: {{ .CertManagerWebhookRepository }}
    tag: {{ .CertManagerWebhookTag }}
  cluster-api/cluster-api-controller:
    repository: {{ .ClusterApiControllerRepository }}
    tag: {{ .ClusterApiControllerTag }}
  bootstrap-kubeadm/kubeadm-bootstrap-controller:
    repository: {{ .KubeadmBootstrapControllerRepository }}
    tag: {{ .KubeadmBootstrapControllerTag }}
  control-plane-kubeadm/kubeadm-control-plane-controller:
    repository: {{ .KubeadmControlPlaneControllerRepository }}
    tag: {{ .KubeadmControlPlaneControllerTag }}
  infrastructure-aws/cluster-api-aws-controller:
    repository: {{ .ClusterApiAwsControllerRepository }}
    tag: {{ .ClusterApiAwsControllerTag }}
  infrastructure-vsphere/manager:
    repository: {{ .ClusterApiVSphereControllerRepository }}
    tag: {{ .ClusterApiVSphereControllerTag }}
  infrastructure-docker/capd-manager:
    repository: {{.DockerManagerRepository}}
    tag: {{.DockerManagerTag}}
  bootstrap-etcdadm-bootstrap/etcdadm-bootstrap-provider:
    repository: {{ .EtcdadmBootstrapProviderRepository }}
    tag: {{ .EtcdadmBootstrapProviderTag }}
  bootstrap-etcdadm-controller/etcdadm-controller:
    repository: {{ .EtcdadmControllerRepository }}
    tag: {{ .EtcdadmControllerTag }}
cert-manager:
  timeout: 30m
  url: "{{.dir}}/cert-manager/{{.CertManagerVersion}}/cert-manager.yaml"
  version: {{.CertManagerVersion}}