server = "https://{{.Server}}"

[host."https://{{.Host}}"]
  capabilities = ["pull", "resolve"]
{{- if .CACertPath }}
  ca = "{{.CACertPath}}"
{{- else }}
  skip_verify = true
{{- end }}
{{- if .AuthHeader }}
  [host."https://{{.Host}}".header]
    authorization = "{{.AuthHeader}}"
{{- end }}
