// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/clusterapi/machinehealthcheck/reconciler/reconciler.go
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=pkg/clusterapi/machinehealthcheck/mocks/reconciler.go -package=mocks -source pkg/clusterapi/machinehealthcheck/reconciler/reconciler.go
//

// Package mocks is a generated GoMock package.
package mocks
