apiVersion: v1
kind: Namespace
metadata:
  name: eksa-system
---
apiVersion: v1
kind: Secret
metadata:
  name: eksa-license
  namespace: eksa-system
stringData:
  license: "{{.eksaLicense}}"
type: Opaque