apiVersion: v1
kind: Namespace
metadata:
  name: eksa-system
---
apiVersion: v1
kind: Secret
metadata:
  name: eksa-license
  namespace: eksa-system
stringData:
  license: "{{.eksaLicense}}"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudstack-credentials
  namespace: eksa-system
type: kubernetes.io/basic-auth
stringData:
  username: "{{.cloudstackUsername}}"
  password: "{{.cloudstackPassword}}"