// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/eks-anywhere/pkg/clustermanager (interfaces: ClusterClient,EKSAComponents,KubernetesClient,ClientFactory,ClusterApplier,CAPIClient)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=pkg/clustermanager/mocks/client_and_networking.go -package=mocks github.com/aws/eks-anywhere/pkg/clustermanager ClusterClient,EKSAComponents,KubernetesClient,ClientFactory,ClusterApplier,CAPIClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/aws/eks-anywhere/pkg/api/v1alpha1"
	kubernetes "github.com/aws/eks-anywhere/pkg/clients/kubernetes"
	cluster "github.com/aws/eks-anywhere/pkg/cluster"
	executables "github.com/aws/eks-anywhere/pkg/executables"
	filewriter "github.com/aws/eks-anywhere/pkg/filewriter"
	providers "github.com/aws/eks-anywhere/pkg/providers"
	types "github.com/aws/eks-anywhere/pkg/types"
	v1alpha10 "github.com/aws/eks-anywhere/release/api/v1alpha1"
	v1alpha11 "github.com/aws/eks-distro-build-tooling/release/api/v1alpha1"
	logr "github.com/go-logr/logr"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1beta2 "sigs.k8s.io/cluster-api/api/controlplane/kubeadm/v1beta2"
	v1beta20 "sigs.k8s.io/cluster-api/api/core/v1beta2"
)

// MockClusterClient is a mock of ClusterClient interface.
type MockClusterClient struct {
	ctrl     *gomock.Controller
	recorder *MockClusterClientMockRecorder
	isgomock struct{}
}

// MockClusterClientMockRecorder is the mock recorder for MockClusterClient.
type MockClusterClientMockRecorder struct {
	mock *MockClusterClient
}

// NewMockClusterClient creates a new mock instance.
func NewMockClusterClient(ctrl *gomock.Controller) *MockClusterClient {
	mock := &MockClusterClient{ctrl: ctrl}
	mock.recorder = &MockClusterClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterClient) EXPECT() *MockClusterClientMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockClusterClient) Apply(ctx context.Context, kubeconfigPath string, obj runtime.Object, opts ...kubernetes.KubectlApplyOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, kubeconfigPath, obj}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Apply", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockClusterClientMockRecorder) Apply(ctx, kubeconfigPath, obj any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, kubeconfigPath, obj}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockClusterClient)(nil).Apply), varargs...)
}

// ApplyKubeSpecFromBytes mocks base method.
func (m *MockClusterClient) ApplyKubeSpecFromBytes(ctx context.Context, arg1 *types.Cluster, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyKubeSpecFromBytes", ctx, arg1, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyKubeSpecFromBytes indicates an expected call of ApplyKubeSpecFromBytes.
func (mr *MockClusterClientMockRecorder) ApplyKubeSpecFromBytes(ctx, arg1, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyKubeSpecFromBytes", reflect.TypeOf((*MockClusterClient)(nil).ApplyKubeSpecFromBytes), ctx, arg1, data)
}

// ApplyKubeSpecFromBytesForce mocks base method.
func (m *MockClusterClient) ApplyKubeSpecFromBytesForce(ctx context.Context, arg1 *types.Cluster, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyKubeSpecFromBytesForce", ctx, arg1, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyKubeSpecFromBytesForce indicates an expected call of ApplyKubeSpecFromBytesForce.
func (mr *MockClusterClientMockRecorder) ApplyKubeSpecFromBytesForce(ctx, arg1, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyKubeSpecFromBytesForce", reflect.TypeOf((*MockClusterClient)(nil).ApplyKubeSpecFromBytesForce), ctx, arg1, data)
}

// ApplyKubeSpecFromBytesWithNamespace mocks base method.
func (m *MockClusterClient) ApplyKubeSpecFromBytesWithNamespace(ctx context.Context, arg1 *types.Cluster, data []byte, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyKubeSpecFromBytesWithNamespace", ctx, arg1, data, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyKubeSpecFromBytesWithNamespace indicates an expected call of ApplyKubeSpecFromBytesWithNamespace.
func (mr *MockClusterClientMockRecorder) ApplyKubeSpecFromBytesWithNamespace(ctx, arg1, data, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyKubeSpecFromBytesWithNamespace", reflect.TypeOf((*MockClusterClient)(nil).ApplyKubeSpecFromBytesWithNamespace), ctx, arg1, data, namespace)
}

// BackupManagement mocks base method.
func (m *MockClusterClient) BackupManagement(ctx context.Context, arg1 *types.Cluster, managementStatePath, clusterName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackupManagement", ctx, arg1, managementStatePath, clusterName)
	ret0, _ := ret[0].(error)
	return ret0
}

// BackupManagement indicates an expected call of BackupManagement.
func (mr *MockClusterClientMockRecorder) BackupManagement(ctx, arg1, managementStatePath, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackupManagement", reflect.TypeOf((*MockClusterClient)(nil).BackupManagement), ctx, arg1, managementStatePath, clusterName)
}

// CountMachineDeploymentReplicasReady mocks base method.
func (m *MockClusterClient) CountMachineDeploymentReplicasReady(ctx context.Context, clusterName, kubeconfigFile string) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMachineDeploymentReplicasReady", ctx, clusterName, kubeconfigFile)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CountMachineDeploymentReplicasReady indicates an expected call of CountMachineDeploymentReplicasReady.
func (mr *MockClusterClientMockRecorder) CountMachineDeploymentReplicasReady(ctx, clusterName, kubeconfigFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMachineDeploymentReplicasReady", reflect.TypeOf((*MockClusterClient)(nil).CountMachineDeploymentReplicasReady), ctx, clusterName, kubeconfigFile)
}

// CreateNamespaceIfNotPresent mocks base method.
func (m *MockClusterClient) CreateNamespaceIfNotPresent(ctx context.Context, kubeconfig, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNamespaceIfNotPresent", ctx, kubeconfig, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNamespaceIfNotPresent indicates an expected call of CreateNamespaceIfNotPresent.
func (mr *MockClusterClientMockRecorder) CreateNamespaceIfNotPresent(ctx, kubeconfig, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNamespaceIfNotPresent", reflect.TypeOf((*MockClusterClient)(nil).CreateNamespaceIfNotPresent), ctx, kubeconfig, namespace)
}

// DeleteAWSIamConfig mocks base method.
func (m *MockClusterClient) DeleteAWSIamConfig(ctx context.Context, arg1 *types.Cluster, name, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAWSIamConfig", ctx, arg1, name, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAWSIamConfig indicates an expected call of DeleteAWSIamConfig.
func (mr *MockClusterClientMockRecorder) DeleteAWSIamConfig(ctx, arg1, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAWSIamConfig", reflect.TypeOf((*MockClusterClient)(nil).DeleteAWSIamConfig), ctx, arg1, name, namespace)
}

// DeleteCluster mocks base method.
func (m *MockClusterClient) DeleteCluster(ctx context.Context, arg1, clusterToDelete *types.Cluster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCluster", ctx, arg1, clusterToDelete)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCluster indicates an expected call of DeleteCluster.
func (mr *MockClusterClientMockRecorder) DeleteCluster(ctx, arg1, clusterToDelete any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCluster", reflect.TypeOf((*MockClusterClient)(nil).DeleteCluster), ctx, arg1, clusterToDelete)
}

// DeleteEKSACluster mocks base method.
func (m *MockClusterClient) DeleteEKSACluster(ctx context.Context, arg1 *types.Cluster, name, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEKSACluster", ctx, arg1, name, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEKSACluster indicates an expected call of DeleteEKSACluster.
func (mr *MockClusterClientMockRecorder) DeleteEKSACluster(ctx, arg1, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEKSACluster", reflect.TypeOf((*MockClusterClient)(nil).DeleteEKSACluster), ctx, arg1, name, namespace)
}

// DeleteGitOpsConfig mocks base method.
func (m *MockClusterClient) DeleteGitOpsConfig(ctx context.Context, arg1 *types.Cluster, name, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGitOpsConfig", ctx, arg1, name, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGitOpsConfig indicates an expected call of DeleteGitOpsConfig.
func (mr *MockClusterClientMockRecorder) DeleteGitOpsConfig(ctx, arg1, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGitOpsConfig", reflect.TypeOf((*MockClusterClient)(nil).DeleteGitOpsConfig), ctx, arg1, name, namespace)
}

// DeleteOIDCConfig mocks base method.
func (m *MockClusterClient) DeleteOIDCConfig(ctx context.Context, arg1 *types.Cluster, name, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOIDCConfig", ctx, arg1, name, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOIDCConfig indicates an expected call of DeleteOIDCConfig.
func (mr *MockClusterClientMockRecorder) DeleteOIDCConfig(ctx, arg1, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOIDCConfig", reflect.TypeOf((*MockClusterClient)(nil).DeleteOIDCConfig), ctx, arg1, name, namespace)
}

// DeleteOldWorkerNodeGroup mocks base method.
func (m *MockClusterClient) DeleteOldWorkerNodeGroup(ctx context.Context, machineDeployment *v1beta20.MachineDeployment, kubeconfig string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldWorkerNodeGroup", ctx, machineDeployment, kubeconfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOldWorkerNodeGroup indicates an expected call of DeleteOldWorkerNodeGroup.
func (mr *MockClusterClientMockRecorder) DeleteOldWorkerNodeGroup(ctx, machineDeployment, kubeconfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldWorkerNodeGroup", reflect.TypeOf((*MockClusterClient)(nil).DeleteOldWorkerNodeGroup), ctx, machineDeployment, kubeconfig)
}

// GetApiServerUrl mocks base method.
func (m *MockClusterClient) GetApiServerUrl(ctx context.Context, arg1 *types.Cluster) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiServerUrl", ctx, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiServerUrl indicates an expected call of GetApiServerUrl.
func (mr *MockClusterClientMockRecorder) GetApiServerUrl(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiServerUrl", reflect.TypeOf((*MockClusterClient)(nil).GetApiServerUrl), ctx, arg1)
}

// GetBundles mocks base method.
func (m *MockClusterClient) GetBundles(ctx context.Context, kubeconfigFile, name, namespace string) (*v1alpha10.Bundles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBundles", ctx, kubeconfigFile, name, namespace)
	ret0, _ := ret[0].(*v1alpha10.Bundles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBundles indicates an expected call of GetBundles.
func (mr *MockClusterClientMockRecorder) GetBundles(ctx, kubeconfigFile, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBundles", reflect.TypeOf((*MockClusterClient)(nil).GetBundles), ctx, kubeconfigFile, name, namespace)
}

// GetClusters mocks base method.
func (m *MockClusterClient) GetClusters(ctx context.Context, arg1 *types.Cluster) ([]types.CAPICluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusters", ctx, arg1)
	ret0, _ := ret[0].([]types.CAPICluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusters indicates an expected call of GetClusters.
func (mr *MockClusterClientMockRecorder) GetClusters(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusters", reflect.TypeOf((*MockClusterClient)(nil).GetClusters), ctx, arg1)
}

// GetConfigMap mocks base method.
func (m *MockClusterClient) GetConfigMap(ctx context.Context, kubeconfigFile, name, namespace string) (*v1.ConfigMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigMap", ctx, kubeconfigFile, name, namespace)
	ret0, _ := ret[0].(*v1.ConfigMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigMap indicates an expected call of GetConfigMap.
func (mr *MockClusterClientMockRecorder) GetConfigMap(ctx, kubeconfigFile, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigMap", reflect.TypeOf((*MockClusterClient)(nil).GetConfigMap), ctx, kubeconfigFile, name, namespace)
}

// GetEksaAWSIamConfig mocks base method.
func (m *MockClusterClient) GetEksaAWSIamConfig(ctx context.Context, awsIamConfigName, kubeconfigFile, namespace string) (*v1alpha1.AWSIamConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksaAWSIamConfig", ctx, awsIamConfigName, kubeconfigFile, namespace)
	ret0, _ := ret[0].(*v1alpha1.AWSIamConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksaAWSIamConfig indicates an expected call of GetEksaAWSIamConfig.
func (mr *MockClusterClientMockRecorder) GetEksaAWSIamConfig(ctx, awsIamConfigName, kubeconfigFile, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksaAWSIamConfig", reflect.TypeOf((*MockClusterClient)(nil).GetEksaAWSIamConfig), ctx, awsIamConfigName, kubeconfigFile, namespace)
}

// GetEksaCloudStackMachineConfig mocks base method.
func (m *MockClusterClient) GetEksaCloudStackMachineConfig(ctx context.Context, cloudstackMachineConfigName, kubeconfigFile, namespace string) (*v1alpha1.CloudStackMachineConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksaCloudStackMachineConfig", ctx, cloudstackMachineConfigName, kubeconfigFile, namespace)
	ret0, _ := ret[0].(*v1alpha1.CloudStackMachineConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksaCloudStackMachineConfig indicates an expected call of GetEksaCloudStackMachineConfig.
func (mr *MockClusterClientMockRecorder) GetEksaCloudStackMachineConfig(ctx, cloudstackMachineConfigName, kubeconfigFile, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksaCloudStackMachineConfig", reflect.TypeOf((*MockClusterClient)(nil).GetEksaCloudStackMachineConfig), ctx, cloudstackMachineConfigName, kubeconfigFile, namespace)
}

// GetEksaCluster mocks base method.
func (m *MockClusterClient) GetEksaCluster(ctx context.Context, arg1 *types.Cluster, clusterName string) (*v1alpha1.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksaCluster", ctx, arg1, clusterName)
	ret0, _ := ret[0].(*v1alpha1.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksaCluster indicates an expected call of GetEksaCluster.
func (mr *MockClusterClientMockRecorder) GetEksaCluster(ctx, arg1, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksaCluster", reflect.TypeOf((*MockClusterClient)(nil).GetEksaCluster), ctx, arg1, clusterName)
}

// GetEksaFluxConfig mocks base method.
func (m *MockClusterClient) GetEksaFluxConfig(ctx context.Context, fluxConfigName, kubeconfigFile, namespace string) (*v1alpha1.FluxConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksaFluxConfig", ctx, fluxConfigName, kubeconfigFile, namespace)
	ret0, _ := ret[0].(*v1alpha1.FluxConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksaFluxConfig indicates an expected call of GetEksaFluxConfig.
func (mr *MockClusterClientMockRecorder) GetEksaFluxConfig(ctx, fluxConfigName, kubeconfigFile, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksaFluxConfig", reflect.TypeOf((*MockClusterClient)(nil).GetEksaFluxConfig), ctx, fluxConfigName, kubeconfigFile, namespace)
}

// GetEksaGitOpsConfig mocks base method.
func (m *MockClusterClient) GetEksaGitOpsConfig(ctx context.Context, gitOpsConfigName, kubeconfigFile, namespace string) (*v1alpha1.GitOpsConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksaGitOpsConfig", ctx, gitOpsConfigName, kubeconfigFile, namespace)
	ret0, _ := ret[0].(*v1alpha1.GitOpsConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksaGitOpsConfig indicates an expected call of GetEksaGitOpsConfig.
func (mr *MockClusterClientMockRecorder) GetEksaGitOpsConfig(ctx, gitOpsConfigName, kubeconfigFile, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksaGitOpsConfig", reflect.TypeOf((*MockClusterClient)(nil).GetEksaGitOpsConfig), ctx, gitOpsConfigName, kubeconfigFile, namespace)
}

// GetEksaOIDCConfig mocks base method.
func (m *MockClusterClient) GetEksaOIDCConfig(ctx context.Context, oidcConfigName, kubeconfigFile, namespace string) (*v1alpha1.OIDCConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksaOIDCConfig", ctx, oidcConfigName, kubeconfigFile, namespace)
	ret0, _ := ret[0].(*v1alpha1.OIDCConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksaOIDCConfig indicates an expected call of GetEksaOIDCConfig.
func (mr *MockClusterClientMockRecorder) GetEksaOIDCConfig(ctx, oidcConfigName, kubeconfigFile, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksaOIDCConfig", reflect.TypeOf((*MockClusterClient)(nil).GetEksaOIDCConfig), ctx, oidcConfigName, kubeconfigFile, namespace)
}

// GetEksaVSphereDatacenterConfig mocks base method.
func (m *MockClusterClient) GetEksaVSphereDatacenterConfig(ctx context.Context, VSphereDatacenterName, kubeconfigFile, namespace string) (*v1alpha1.VSphereDatacenterConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksaVSphereDatacenterConfig", ctx, VSphereDatacenterName, kubeconfigFile, namespace)
	ret0, _ := ret[0].(*v1alpha1.VSphereDatacenterConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksaVSphereDatacenterConfig indicates an expected call of GetEksaVSphereDatacenterConfig.
func (mr *MockClusterClientMockRecorder) GetEksaVSphereDatacenterConfig(ctx, VSphereDatacenterName, kubeconfigFile, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksaVSphereDatacenterConfig", reflect.TypeOf((*MockClusterClient)(nil).GetEksaVSphereDatacenterConfig), ctx, VSphereDatacenterName, kubeconfigFile, namespace)
}

// GetEksaVSphereMachineConfig mocks base method.
func (m *MockClusterClient) GetEksaVSphereMachineConfig(ctx context.Context, VSphereDatacenterName, kubeconfigFile, namespace string) (*v1alpha1.VSphereMachineConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksaVSphereMachineConfig", ctx, VSphereDatacenterName, kubeconfigFile, namespace)
	ret0, _ := ret[0].(*v1alpha1.VSphereMachineConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksaVSphereMachineConfig indicates an expected call of GetEksaVSphereMachineConfig.
func (mr *MockClusterClientMockRecorder) GetEksaVSphereMachineConfig(ctx, VSphereDatacenterName, kubeconfigFile, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksaVSphereMachineConfig", reflect.TypeOf((*MockClusterClient)(nil).GetEksaVSphereMachineConfig), ctx, VSphereDatacenterName, kubeconfigFile, namespace)
}

// GetEksdRelease mocks base method.
func (m *MockClusterClient) GetEksdRelease(ctx context.Context, name, namespace, kubeconfigFile string) (*v1alpha11.Release, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksdRelease", ctx, name, namespace, kubeconfigFile)
	ret0, _ := ret[0].(*v1alpha11.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksdRelease indicates an expected call of GetEksdRelease.
func (mr *MockClusterClientMockRecorder) GetEksdRelease(ctx, name, namespace, kubeconfigFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksdRelease", reflect.TypeOf((*MockClusterClient)(nil).GetEksdRelease), ctx, name, namespace, kubeconfigFile)
}

// GetKubeadmControlPlane mocks base method.
func (m *MockClusterClient) GetKubeadmControlPlane(ctx context.Context, arg1 *types.Cluster, clusterName string, opts ...executables.KubectlOpt) (*v1beta2.KubeadmControlPlane, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, arg1, clusterName}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetKubeadmControlPlane", varargs...)
	ret0, _ := ret[0].(*v1beta2.KubeadmControlPlane)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKubeadmControlPlane indicates an expected call of GetKubeadmControlPlane.
func (mr *MockClusterClientMockRecorder) GetKubeadmControlPlane(ctx, arg1, clusterName any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, arg1, clusterName}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKubeadmControlPlane", reflect.TypeOf((*MockClusterClient)(nil).GetKubeadmControlPlane), varargs...)
}

// GetMachineDeployment mocks base method.
func (m *MockClusterClient) GetMachineDeployment(ctx context.Context, workerNodeGroupName string, opts ...executables.KubectlOpt) (*v1beta20.MachineDeployment, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, workerNodeGroupName}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMachineDeployment", varargs...)
	ret0, _ := ret[0].(*v1beta20.MachineDeployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachineDeployment indicates an expected call of GetMachineDeployment.
func (mr *MockClusterClientMockRecorder) GetMachineDeployment(ctx, workerNodeGroupName any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, workerNodeGroupName}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachineDeployment", reflect.TypeOf((*MockClusterClient)(nil).GetMachineDeployment), varargs...)
}

// GetMachineDeploymentsForCluster mocks base method.
func (m *MockClusterClient) GetMachineDeploymentsForCluster(ctx context.Context, clusterName string, opts ...executables.KubectlOpt) ([]v1beta20.MachineDeployment, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, clusterName}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMachineDeploymentsForCluster", varargs...)
	ret0, _ := ret[0].([]v1beta20.MachineDeployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachineDeploymentsForCluster indicates an expected call of GetMachineDeploymentsForCluster.
func (mr *MockClusterClientMockRecorder) GetMachineDeploymentsForCluster(ctx, clusterName any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, clusterName}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachineDeploymentsForCluster", reflect.TypeOf((*MockClusterClient)(nil).GetMachineDeploymentsForCluster), varargs...)
}

// GetMachines mocks base method.
func (m *MockClusterClient) GetMachines(ctx context.Context, arg1 *types.Cluster, clusterName string) ([]types.Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMachines", ctx, arg1, clusterName)
	ret0, _ := ret[0].([]types.Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachines indicates an expected call of GetMachines.
func (mr *MockClusterClientMockRecorder) GetMachines(ctx, arg1, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachines", reflect.TypeOf((*MockClusterClient)(nil).GetMachines), ctx, arg1, clusterName)
}

// GetWorkloadKubeconfig mocks base method.
func (m *MockClusterClient) GetWorkloadKubeconfig(ctx context.Context, clusterName string, arg2 *types.Cluster) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkloadKubeconfig", ctx, clusterName, arg2)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkloadKubeconfig indicates an expected call of GetWorkloadKubeconfig.
func (mr *MockClusterClientMockRecorder) GetWorkloadKubeconfig(ctx, clusterName, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkloadKubeconfig", reflect.TypeOf((*MockClusterClient)(nil).GetWorkloadKubeconfig), ctx, clusterName, arg2)
}

// InitInfrastructure mocks base method.
func (m *MockClusterClient) InitInfrastructure(ctx context.Context, managementComponents *cluster.ManagementComponents, clusterSpec *cluster.Spec, arg3 *types.Cluster, provider providers.Provider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitInfrastructure", ctx, managementComponents, clusterSpec, arg3, provider)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitInfrastructure indicates an expected call of InitInfrastructure.
func (mr *MockClusterClientMockRecorder) InitInfrastructure(ctx, managementComponents, clusterSpec, arg3, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitInfrastructure", reflect.TypeOf((*MockClusterClient)(nil).InitInfrastructure), ctx, managementComponents, clusterSpec, arg3, provider)
}

// KubeconfigSecretAvailable mocks base method.
func (m *MockClusterClient) KubeconfigSecretAvailable(ctx context.Context, kubeconfig, clusterName, namespace string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KubeconfigSecretAvailable", ctx, kubeconfig, clusterName, namespace)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KubeconfigSecretAvailable indicates an expected call of KubeconfigSecretAvailable.
func (mr *MockClusterClientMockRecorder) KubeconfigSecretAvailable(ctx, kubeconfig, clusterName, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KubeconfigSecretAvailable", reflect.TypeOf((*MockClusterClient)(nil).KubeconfigSecretAvailable), ctx, kubeconfig, clusterName, namespace)
}

// ListObjects mocks base method.
func (m *MockClusterClient) ListObjects(ctx context.Context, resourceType, namespace, kubeconfig string, list kubernetes.ObjectList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, resourceType, namespace, kubeconfig, list)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockClusterClientMockRecorder) ListObjects(ctx, resourceType, namespace, kubeconfig, list any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockClusterClient)(nil).ListObjects), ctx, resourceType, namespace, kubeconfig, list)
}

// MoveManagement mocks base method.
func (m *MockClusterClient) MoveManagement(ctx context.Context, from, target *types.Cluster, clusterName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveManagement", ctx, from, target, clusterName)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveManagement indicates an expected call of MoveManagement.
func (mr *MockClusterClientMockRecorder) MoveManagement(ctx, from, target, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveManagement", reflect.TypeOf((*MockClusterClient)(nil).MoveManagement), ctx, from, target, clusterName)
}

// PauseCAPICluster mocks base method.
func (m *MockClusterClient) PauseCAPICluster(ctx context.Context, arg1, kubeconfig string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseCAPICluster", ctx, arg1, kubeconfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseCAPICluster indicates an expected call of PauseCAPICluster.
func (mr *MockClusterClientMockRecorder) PauseCAPICluster(ctx, arg1, kubeconfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseCAPICluster", reflect.TypeOf((*MockClusterClient)(nil).PauseCAPICluster), ctx, arg1, kubeconfig)
}

// RemoveAnnotationInNamespace mocks base method.
func (m *MockClusterClient) RemoveAnnotationInNamespace(ctx context.Context, resourceType, objectName, key string, arg4 *types.Cluster, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAnnotationInNamespace", ctx, resourceType, objectName, key, arg4, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAnnotationInNamespace indicates an expected call of RemoveAnnotationInNamespace.
func (mr *MockClusterClientMockRecorder) RemoveAnnotationInNamespace(ctx, resourceType, objectName, key, arg4, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAnnotationInNamespace", reflect.TypeOf((*MockClusterClient)(nil).RemoveAnnotationInNamespace), ctx, resourceType, objectName, key, arg4, namespace)
}

// ResumeCAPICluster mocks base method.
func (m *MockClusterClient) ResumeCAPICluster(ctx context.Context, arg1, kubeconfig string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeCAPICluster", ctx, arg1, kubeconfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumeCAPICluster indicates an expected call of ResumeCAPICluster.
func (mr *MockClusterClientMockRecorder) ResumeCAPICluster(ctx, arg1, kubeconfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeCAPICluster", reflect.TypeOf((*MockClusterClient)(nil).ResumeCAPICluster), ctx, arg1, kubeconfig)
}

// SaveLog mocks base method.
func (m *MockClusterClient) SaveLog(ctx context.Context, arg1 *types.Cluster, deployment *types.Deployment, fileName string, writer filewriter.FileWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLog", ctx, arg1, deployment, fileName, writer)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveLog indicates an expected call of SaveLog.
func (mr *MockClusterClientMockRecorder) SaveLog(ctx, arg1, deployment, fileName, writer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLog", reflect.TypeOf((*MockClusterClient)(nil).SaveLog), ctx, arg1, deployment, fileName, writer)
}

// SetEksaControllerEnvVar mocks base method.
func (m *MockClusterClient) SetEksaControllerEnvVar(ctx context.Context, envVar, envVarVal, kubeconfig string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEksaControllerEnvVar", ctx, envVar, envVarVal, kubeconfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEksaControllerEnvVar indicates an expected call of SetEksaControllerEnvVar.
func (mr *MockClusterClientMockRecorder) SetEksaControllerEnvVar(ctx, envVar, envVarVal, kubeconfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEksaControllerEnvVar", reflect.TypeOf((*MockClusterClient)(nil).SetEksaControllerEnvVar), ctx, envVar, envVarVal, kubeconfig)
}

// UpdateAnnotationInNamespace mocks base method.
func (m *MockClusterClient) UpdateAnnotationInNamespace(ctx context.Context, resourceType, objectName string, annotations map[string]string, arg4 *types.Cluster, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAnnotationInNamespace", ctx, resourceType, objectName, annotations, arg4, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAnnotationInNamespace indicates an expected call of UpdateAnnotationInNamespace.
func (mr *MockClusterClientMockRecorder) UpdateAnnotationInNamespace(ctx, resourceType, objectName, annotations, arg4, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAnnotationInNamespace", reflect.TypeOf((*MockClusterClient)(nil).UpdateAnnotationInNamespace), ctx, resourceType, objectName, annotations, arg4, namespace)
}

// UpdateEnvironmentVariablesInNamespace mocks base method.
func (m *MockClusterClient) UpdateEnvironmentVariablesInNamespace(ctx context.Context, resourceType, resourceName string, envMap map[string]string, arg4 *types.Cluster, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEnvironmentVariablesInNamespace", ctx, resourceType, resourceName, envMap, arg4, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEnvironmentVariablesInNamespace indicates an expected call of UpdateEnvironmentVariablesInNamespace.
func (mr *MockClusterClientMockRecorder) UpdateEnvironmentVariablesInNamespace(ctx, resourceType, resourceName, envMap, arg4, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEnvironmentVariablesInNamespace", reflect.TypeOf((*MockClusterClient)(nil).UpdateEnvironmentVariablesInNamespace), ctx, resourceType, resourceName, envMap, arg4, namespace)
}

// ValidateControlPlaneNodes mocks base method.
func (m *MockClusterClient) ValidateControlPlaneNodes(ctx context.Context, arg1 *types.Cluster, clusterName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateControlPlaneNodes", ctx, arg1, clusterName)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateControlPlaneNodes indicates an expected call of ValidateControlPlaneNodes.
func (mr *MockClusterClientMockRecorder) ValidateControlPlaneNodes(ctx, arg1, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateControlPlaneNodes", reflect.TypeOf((*MockClusterClient)(nil).ValidateControlPlaneNodes), ctx, arg1, clusterName)
}

// ValidateWorkerNodes mocks base method.
func (m *MockClusterClient) ValidateWorkerNodes(ctx context.Context, clusterName, kubeconfigFile string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateWorkerNodes", ctx, clusterName, kubeconfigFile)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateWorkerNodes indicates an expected call of ValidateWorkerNodes.
func (mr *MockClusterClientMockRecorder) ValidateWorkerNodes(ctx, clusterName, kubeconfigFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateWorkerNodes", reflect.TypeOf((*MockClusterClient)(nil).ValidateWorkerNodes), ctx, clusterName, kubeconfigFile)
}

// WaitForClusterReady mocks base method.
func (m *MockClusterClient) WaitForClusterReady(ctx context.Context, arg1 *types.Cluster, timeout, clusterName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForClusterReady", ctx, arg1, timeout, clusterName)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForClusterReady indicates an expected call of WaitForClusterReady.
func (mr *MockClusterClientMockRecorder) WaitForClusterReady(ctx, arg1, timeout, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForClusterReady", reflect.TypeOf((*MockClusterClient)(nil).WaitForClusterReady), ctx, arg1, timeout, clusterName)
}

// WaitForControlPlaneReady mocks base method.
func (m *MockClusterClient) WaitForControlPlaneReady(ctx context.Context, arg1 *types.Cluster, timeout, newClusterName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForControlPlaneReady", ctx, arg1, timeout, newClusterName)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForControlPlaneReady indicates an expected call of WaitForControlPlaneReady.
func (mr *MockClusterClientMockRecorder) WaitForControlPlaneReady(ctx, arg1, timeout, newClusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForControlPlaneReady", reflect.TypeOf((*MockClusterClient)(nil).WaitForControlPlaneReady), ctx, arg1, timeout, newClusterName)
}

// WaitForDeployment mocks base method.
func (m *MockClusterClient) WaitForDeployment(ctx context.Context, arg1 *types.Cluster, timeout, condition, target, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForDeployment", ctx, arg1, timeout, condition, target, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForDeployment indicates an expected call of WaitForDeployment.
func (mr *MockClusterClientMockRecorder) WaitForDeployment(ctx, arg1, timeout, condition, target, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForDeployment", reflect.TypeOf((*MockClusterClient)(nil).WaitForDeployment), ctx, arg1, timeout, condition, target, namespace)
}

// MockEKSAComponents is a mock of EKSAComponents interface.
type MockEKSAComponents struct {
	ctrl     *gomock.Controller
	recorder *MockEKSAComponentsMockRecorder
	isgomock struct{}
}

// MockEKSAComponentsMockRecorder is the mock recorder for MockEKSAComponents.
type MockEKSAComponentsMockRecorder struct {
	mock *MockEKSAComponents
}

// NewMockEKSAComponents creates a new mock instance.
func NewMockEKSAComponents(ctrl *gomock.Controller) *MockEKSAComponents {
	mock := &MockEKSAComponents{ctrl: ctrl}
	mock.recorder = &MockEKSAComponentsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEKSAComponents) EXPECT() *MockEKSAComponentsMockRecorder {
	return m.recorder
}

// Install mocks base method.
func (m *MockEKSAComponents) Install(ctx context.Context, log logr.Logger, arg2 *types.Cluster, managementComponents *cluster.ManagementComponents, spec *cluster.Spec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Install", ctx, log, arg2, managementComponents, spec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Install indicates an expected call of Install.
func (mr *MockEKSAComponentsMockRecorder) Install(ctx, log, arg2, managementComponents, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockEKSAComponents)(nil).Install), ctx, log, arg2, managementComponents, spec)
}

// Upgrade mocks base method.
func (m *MockEKSAComponents) Upgrade(ctx context.Context, log logr.Logger, arg2 *types.Cluster, currentManagementComponents, newManagementComponents *cluster.ManagementComponents, newSpec *cluster.Spec) (*types.ChangeDiff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upgrade", ctx, log, arg2, currentManagementComponents, newManagementComponents, newSpec)
	ret0, _ := ret[0].(*types.ChangeDiff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upgrade indicates an expected call of Upgrade.
func (mr *MockEKSAComponentsMockRecorder) Upgrade(ctx, log, arg2, currentManagementComponents, newManagementComponents, newSpec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upgrade", reflect.TypeOf((*MockEKSAComponents)(nil).Upgrade), ctx, log, arg2, currentManagementComponents, newManagementComponents, newSpec)
}

// MockKubernetesClient is a mock of KubernetesClient interface.
type MockKubernetesClient struct {
	ctrl     *gomock.Controller
	recorder *MockKubernetesClientMockRecorder
	isgomock struct{}
}

// MockKubernetesClientMockRecorder is the mock recorder for MockKubernetesClient.
type MockKubernetesClientMockRecorder struct {
	mock *MockKubernetesClient
}

// NewMockKubernetesClient creates a new mock instance.
func NewMockKubernetesClient(ctrl *gomock.Controller) *MockKubernetesClient {
	mock := &MockKubernetesClient{ctrl: ctrl}
	mock.recorder = &MockKubernetesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubernetesClient) EXPECT() *MockKubernetesClientMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockKubernetesClient) Apply(ctx context.Context, kubeconfigPath string, obj runtime.Object, opts ...kubernetes.KubectlApplyOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, kubeconfigPath, obj}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Apply", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockKubernetesClientMockRecorder) Apply(ctx, kubeconfigPath, obj any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, kubeconfigPath, obj}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockKubernetesClient)(nil).Apply), varargs...)
}

// ApplyKubeSpecFromBytes mocks base method.
func (m *MockKubernetesClient) ApplyKubeSpecFromBytes(ctx context.Context, arg1 *types.Cluster, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyKubeSpecFromBytes", ctx, arg1, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyKubeSpecFromBytes indicates an expected call of ApplyKubeSpecFromBytes.
func (mr *MockKubernetesClientMockRecorder) ApplyKubeSpecFromBytes(ctx, arg1, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyKubeSpecFromBytes", reflect.TypeOf((*MockKubernetesClient)(nil).ApplyKubeSpecFromBytes), ctx, arg1, data)
}

// ApplyKubeSpecFromBytesForce mocks base method.
func (m *MockKubernetesClient) ApplyKubeSpecFromBytesForce(ctx context.Context, arg1 *types.Cluster, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyKubeSpecFromBytesForce", ctx, arg1, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyKubeSpecFromBytesForce indicates an expected call of ApplyKubeSpecFromBytesForce.
func (mr *MockKubernetesClientMockRecorder) ApplyKubeSpecFromBytesForce(ctx, arg1, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyKubeSpecFromBytesForce", reflect.TypeOf((*MockKubernetesClient)(nil).ApplyKubeSpecFromBytesForce), ctx, arg1, data)
}

// ApplyKubeSpecFromBytesWithNamespace mocks base method.
func (m *MockKubernetesClient) ApplyKubeSpecFromBytesWithNamespace(ctx context.Context, arg1 *types.Cluster, data []byte, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyKubeSpecFromBytesWithNamespace", ctx, arg1, data, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyKubeSpecFromBytesWithNamespace indicates an expected call of ApplyKubeSpecFromBytesWithNamespace.
func (mr *MockKubernetesClientMockRecorder) ApplyKubeSpecFromBytesWithNamespace(ctx, arg1, data, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyKubeSpecFromBytesWithNamespace", reflect.TypeOf((*MockKubernetesClient)(nil).ApplyKubeSpecFromBytesWithNamespace), ctx, arg1, data, namespace)
}

// CountMachineDeploymentReplicasReady mocks base method.
func (m *MockKubernetesClient) CountMachineDeploymentReplicasReady(ctx context.Context, clusterName, kubeconfigFile string) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMachineDeploymentReplicasReady", ctx, clusterName, kubeconfigFile)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CountMachineDeploymentReplicasReady indicates an expected call of CountMachineDeploymentReplicasReady.
func (mr *MockKubernetesClientMockRecorder) CountMachineDeploymentReplicasReady(ctx, clusterName, kubeconfigFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMachineDeploymentReplicasReady", reflect.TypeOf((*MockKubernetesClient)(nil).CountMachineDeploymentReplicasReady), ctx, clusterName, kubeconfigFile)
}

// CreateNamespaceIfNotPresent mocks base method.
func (m *MockKubernetesClient) CreateNamespaceIfNotPresent(ctx context.Context, kubeconfig, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNamespaceIfNotPresent", ctx, kubeconfig, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNamespaceIfNotPresent indicates an expected call of CreateNamespaceIfNotPresent.
func (mr *MockKubernetesClientMockRecorder) CreateNamespaceIfNotPresent(ctx, kubeconfig, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNamespaceIfNotPresent", reflect.TypeOf((*MockKubernetesClient)(nil).CreateNamespaceIfNotPresent), ctx, kubeconfig, namespace)
}

// DeleteAWSIamConfig mocks base method.
func (m *MockKubernetesClient) DeleteAWSIamConfig(ctx context.Context, arg1 *types.Cluster, name, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAWSIamConfig", ctx, arg1, name, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAWSIamConfig indicates an expected call of DeleteAWSIamConfig.
func (mr *MockKubernetesClientMockRecorder) DeleteAWSIamConfig(ctx, arg1, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAWSIamConfig", reflect.TypeOf((*MockKubernetesClient)(nil).DeleteAWSIamConfig), ctx, arg1, name, namespace)
}

// DeleteCluster mocks base method.
func (m *MockKubernetesClient) DeleteCluster(ctx context.Context, arg1, clusterToDelete *types.Cluster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCluster", ctx, arg1, clusterToDelete)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCluster indicates an expected call of DeleteCluster.
func (mr *MockKubernetesClientMockRecorder) DeleteCluster(ctx, arg1, clusterToDelete any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCluster", reflect.TypeOf((*MockKubernetesClient)(nil).DeleteCluster), ctx, arg1, clusterToDelete)
}

// DeleteEKSACluster mocks base method.
func (m *MockKubernetesClient) DeleteEKSACluster(ctx context.Context, arg1 *types.Cluster, name, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEKSACluster", ctx, arg1, name, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEKSACluster indicates an expected call of DeleteEKSACluster.
func (mr *MockKubernetesClientMockRecorder) DeleteEKSACluster(ctx, arg1, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEKSACluster", reflect.TypeOf((*MockKubernetesClient)(nil).DeleteEKSACluster), ctx, arg1, name, namespace)
}

// DeleteGitOpsConfig mocks base method.
func (m *MockKubernetesClient) DeleteGitOpsConfig(ctx context.Context, arg1 *types.Cluster, name, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGitOpsConfig", ctx, arg1, name, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGitOpsConfig indicates an expected call of DeleteGitOpsConfig.
func (mr *MockKubernetesClientMockRecorder) DeleteGitOpsConfig(ctx, arg1, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGitOpsConfig", reflect.TypeOf((*MockKubernetesClient)(nil).DeleteGitOpsConfig), ctx, arg1, name, namespace)
}

// DeleteOIDCConfig mocks base method.
func (m *MockKubernetesClient) DeleteOIDCConfig(ctx context.Context, arg1 *types.Cluster, name, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOIDCConfig", ctx, arg1, name, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOIDCConfig indicates an expected call of DeleteOIDCConfig.
func (mr *MockKubernetesClientMockRecorder) DeleteOIDCConfig(ctx, arg1, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOIDCConfig", reflect.TypeOf((*MockKubernetesClient)(nil).DeleteOIDCConfig), ctx, arg1, name, namespace)
}

// DeleteOldWorkerNodeGroup mocks base method.
func (m *MockKubernetesClient) DeleteOldWorkerNodeGroup(ctx context.Context, machineDeployment *v1beta20.MachineDeployment, kubeconfig string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldWorkerNodeGroup", ctx, machineDeployment, kubeconfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOldWorkerNodeGroup indicates an expected call of DeleteOldWorkerNodeGroup.
func (mr *MockKubernetesClientMockRecorder) DeleteOldWorkerNodeGroup(ctx, machineDeployment, kubeconfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldWorkerNodeGroup", reflect.TypeOf((*MockKubernetesClient)(nil).DeleteOldWorkerNodeGroup), ctx, machineDeployment, kubeconfig)
}

// GetApiServerUrl mocks base method.
func (m *MockKubernetesClient) GetApiServerUrl(ctx context.Context, arg1 *types.Cluster) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiServerUrl", ctx, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiServerUrl indicates an expected call of GetApiServerUrl.
func (mr *MockKubernetesClientMockRecorder) GetApiServerUrl(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiServerUrl", reflect.TypeOf((*MockKubernetesClient)(nil).GetApiServerUrl), ctx, arg1)
}

// GetBundles mocks base method.
func (m *MockKubernetesClient) GetBundles(ctx context.Context, kubeconfigFile, name, namespace string) (*v1alpha10.Bundles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBundles", ctx, kubeconfigFile, name, namespace)
	ret0, _ := ret[0].(*v1alpha10.Bundles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBundles indicates an expected call of GetBundles.
func (mr *MockKubernetesClientMockRecorder) GetBundles(ctx, kubeconfigFile, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBundles", reflect.TypeOf((*MockKubernetesClient)(nil).GetBundles), ctx, kubeconfigFile, name, namespace)
}

// GetClusters mocks base method.
func (m *MockKubernetesClient) GetClusters(ctx context.Context, arg1 *types.Cluster) ([]types.CAPICluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusters", ctx, arg1)
	ret0, _ := ret[0].([]types.CAPICluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusters indicates an expected call of GetClusters.
func (mr *MockKubernetesClientMockRecorder) GetClusters(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusters", reflect.TypeOf((*MockKubernetesClient)(nil).GetClusters), ctx, arg1)
}

// GetConfigMap mocks base method.
func (m *MockKubernetesClient) GetConfigMap(ctx context.Context, kubeconfigFile, name, namespace string) (*v1.ConfigMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigMap", ctx, kubeconfigFile, name, namespace)
	ret0, _ := ret[0].(*v1.ConfigMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConfigMap indicates an expected call of GetConfigMap.
func (mr *MockKubernetesClientMockRecorder) GetConfigMap(ctx, kubeconfigFile, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigMap", reflect.TypeOf((*MockKubernetesClient)(nil).GetConfigMap), ctx, kubeconfigFile, name, namespace)
}

// GetEksaAWSIamConfig mocks base method.
func (m *MockKubernetesClient) GetEksaAWSIamConfig(ctx context.Context, awsIamConfigName, kubeconfigFile, namespace string) (*v1alpha1.AWSIamConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksaAWSIamConfig", ctx, awsIamConfigName, kubeconfigFile, namespace)
	ret0, _ := ret[0].(*v1alpha1.AWSIamConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksaAWSIamConfig indicates an expected call of GetEksaAWSIamConfig.
func (mr *MockKubernetesClientMockRecorder) GetEksaAWSIamConfig(ctx, awsIamConfigName, kubeconfigFile, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksaAWSIamConfig", reflect.TypeOf((*MockKubernetesClient)(nil).GetEksaAWSIamConfig), ctx, awsIamConfigName, kubeconfigFile, namespace)
}

// GetEksaCloudStackMachineConfig mocks base method.
func (m *MockKubernetesClient) GetEksaCloudStackMachineConfig(ctx context.Context, cloudstackMachineConfigName, kubeconfigFile, namespace string) (*v1alpha1.CloudStackMachineConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksaCloudStackMachineConfig", ctx, cloudstackMachineConfigName, kubeconfigFile, namespace)
	ret0, _ := ret[0].(*v1alpha1.CloudStackMachineConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksaCloudStackMachineConfig indicates an expected call of GetEksaCloudStackMachineConfig.
func (mr *MockKubernetesClientMockRecorder) GetEksaCloudStackMachineConfig(ctx, cloudstackMachineConfigName, kubeconfigFile, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksaCloudStackMachineConfig", reflect.TypeOf((*MockKubernetesClient)(nil).GetEksaCloudStackMachineConfig), ctx, cloudstackMachineConfigName, kubeconfigFile, namespace)
}

// GetEksaCluster mocks base method.
func (m *MockKubernetesClient) GetEksaCluster(ctx context.Context, arg1 *types.Cluster, clusterName string) (*v1alpha1.Cluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksaCluster", ctx, arg1, clusterName)
	ret0, _ := ret[0].(*v1alpha1.Cluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksaCluster indicates an expected call of GetEksaCluster.
func (mr *MockKubernetesClientMockRecorder) GetEksaCluster(ctx, arg1, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksaCluster", reflect.TypeOf((*MockKubernetesClient)(nil).GetEksaCluster), ctx, arg1, clusterName)
}

// GetEksaFluxConfig mocks base method.
func (m *MockKubernetesClient) GetEksaFluxConfig(ctx context.Context, fluxConfigName, kubeconfigFile, namespace string) (*v1alpha1.FluxConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksaFluxConfig", ctx, fluxConfigName, kubeconfigFile, namespace)
	ret0, _ := ret[0].(*v1alpha1.FluxConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksaFluxConfig indicates an expected call of GetEksaFluxConfig.
func (mr *MockKubernetesClientMockRecorder) GetEksaFluxConfig(ctx, fluxConfigName, kubeconfigFile, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksaFluxConfig", reflect.TypeOf((*MockKubernetesClient)(nil).GetEksaFluxConfig), ctx, fluxConfigName, kubeconfigFile, namespace)
}

// GetEksaGitOpsConfig mocks base method.
func (m *MockKubernetesClient) GetEksaGitOpsConfig(ctx context.Context, gitOpsConfigName, kubeconfigFile, namespace string) (*v1alpha1.GitOpsConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksaGitOpsConfig", ctx, gitOpsConfigName, kubeconfigFile, namespace)
	ret0, _ := ret[0].(*v1alpha1.GitOpsConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksaGitOpsConfig indicates an expected call of GetEksaGitOpsConfig.
func (mr *MockKubernetesClientMockRecorder) GetEksaGitOpsConfig(ctx, gitOpsConfigName, kubeconfigFile, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksaGitOpsConfig", reflect.TypeOf((*MockKubernetesClient)(nil).GetEksaGitOpsConfig), ctx, gitOpsConfigName, kubeconfigFile, namespace)
}

// GetEksaOIDCConfig mocks base method.
func (m *MockKubernetesClient) GetEksaOIDCConfig(ctx context.Context, oidcConfigName, kubeconfigFile, namespace string) (*v1alpha1.OIDCConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksaOIDCConfig", ctx, oidcConfigName, kubeconfigFile, namespace)
	ret0, _ := ret[0].(*v1alpha1.OIDCConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksaOIDCConfig indicates an expected call of GetEksaOIDCConfig.
func (mr *MockKubernetesClientMockRecorder) GetEksaOIDCConfig(ctx, oidcConfigName, kubeconfigFile, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksaOIDCConfig", reflect.TypeOf((*MockKubernetesClient)(nil).GetEksaOIDCConfig), ctx, oidcConfigName, kubeconfigFile, namespace)
}

// GetEksaVSphereDatacenterConfig mocks base method.
func (m *MockKubernetesClient) GetEksaVSphereDatacenterConfig(ctx context.Context, VSphereDatacenterName, kubeconfigFile, namespace string) (*v1alpha1.VSphereDatacenterConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksaVSphereDatacenterConfig", ctx, VSphereDatacenterName, kubeconfigFile, namespace)
	ret0, _ := ret[0].(*v1alpha1.VSphereDatacenterConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksaVSphereDatacenterConfig indicates an expected call of GetEksaVSphereDatacenterConfig.
func (mr *MockKubernetesClientMockRecorder) GetEksaVSphereDatacenterConfig(ctx, VSphereDatacenterName, kubeconfigFile, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksaVSphereDatacenterConfig", reflect.TypeOf((*MockKubernetesClient)(nil).GetEksaVSphereDatacenterConfig), ctx, VSphereDatacenterName, kubeconfigFile, namespace)
}

// GetEksaVSphereMachineConfig mocks base method.
func (m *MockKubernetesClient) GetEksaVSphereMachineConfig(ctx context.Context, VSphereDatacenterName, kubeconfigFile, namespace string) (*v1alpha1.VSphereMachineConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksaVSphereMachineConfig", ctx, VSphereDatacenterName, kubeconfigFile, namespace)
	ret0, _ := ret[0].(*v1alpha1.VSphereMachineConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksaVSphereMachineConfig indicates an expected call of GetEksaVSphereMachineConfig.
func (mr *MockKubernetesClientMockRecorder) GetEksaVSphereMachineConfig(ctx, VSphereDatacenterName, kubeconfigFile, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksaVSphereMachineConfig", reflect.TypeOf((*MockKubernetesClient)(nil).GetEksaVSphereMachineConfig), ctx, VSphereDatacenterName, kubeconfigFile, namespace)
}

// GetEksdRelease mocks base method.
func (m *MockKubernetesClient) GetEksdRelease(ctx context.Context, name, namespace, kubeconfigFile string) (*v1alpha11.Release, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEksdRelease", ctx, name, namespace, kubeconfigFile)
	ret0, _ := ret[0].(*v1alpha11.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEksdRelease indicates an expected call of GetEksdRelease.
func (mr *MockKubernetesClientMockRecorder) GetEksdRelease(ctx, name, namespace, kubeconfigFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEksdRelease", reflect.TypeOf((*MockKubernetesClient)(nil).GetEksdRelease), ctx, name, namespace, kubeconfigFile)
}

// GetKubeadmControlPlane mocks base method.
func (m *MockKubernetesClient) GetKubeadmControlPlane(ctx context.Context, arg1 *types.Cluster, clusterName string, opts ...executables.KubectlOpt) (*v1beta2.KubeadmControlPlane, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, arg1, clusterName}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetKubeadmControlPlane", varargs...)
	ret0, _ := ret[0].(*v1beta2.KubeadmControlPlane)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKubeadmControlPlane indicates an expected call of GetKubeadmControlPlane.
func (mr *MockKubernetesClientMockRecorder) GetKubeadmControlPlane(ctx, arg1, clusterName any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, arg1, clusterName}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKubeadmControlPlane", reflect.TypeOf((*MockKubernetesClient)(nil).GetKubeadmControlPlane), varargs...)
}

// GetMachineDeployment mocks base method.
func (m *MockKubernetesClient) GetMachineDeployment(ctx context.Context, workerNodeGroupName string, opts ...executables.KubectlOpt) (*v1beta20.MachineDeployment, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, workerNodeGroupName}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMachineDeployment", varargs...)
	ret0, _ := ret[0].(*v1beta20.MachineDeployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachineDeployment indicates an expected call of GetMachineDeployment.
func (mr *MockKubernetesClientMockRecorder) GetMachineDeployment(ctx, workerNodeGroupName any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, workerNodeGroupName}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachineDeployment", reflect.TypeOf((*MockKubernetesClient)(nil).GetMachineDeployment), varargs...)
}

// GetMachineDeploymentsForCluster mocks base method.
func (m *MockKubernetesClient) GetMachineDeploymentsForCluster(ctx context.Context, clusterName string, opts ...executables.KubectlOpt) ([]v1beta20.MachineDeployment, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, clusterName}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMachineDeploymentsForCluster", varargs...)
	ret0, _ := ret[0].([]v1beta20.MachineDeployment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachineDeploymentsForCluster indicates an expected call of GetMachineDeploymentsForCluster.
func (mr *MockKubernetesClientMockRecorder) GetMachineDeploymentsForCluster(ctx, clusterName any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, clusterName}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachineDeploymentsForCluster", reflect.TypeOf((*MockKubernetesClient)(nil).GetMachineDeploymentsForCluster), varargs...)
}

// GetMachines mocks base method.
func (m *MockKubernetesClient) GetMachines(ctx context.Context, arg1 *types.Cluster, clusterName string) ([]types.Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMachines", ctx, arg1, clusterName)
	ret0, _ := ret[0].([]types.Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachines indicates an expected call of GetMachines.
func (mr *MockKubernetesClientMockRecorder) GetMachines(ctx, arg1, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachines", reflect.TypeOf((*MockKubernetesClient)(nil).GetMachines), ctx, arg1, clusterName)
}

// KubeconfigSecretAvailable mocks base method.
func (m *MockKubernetesClient) KubeconfigSecretAvailable(ctx context.Context, kubeconfig, clusterName, namespace string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KubeconfigSecretAvailable", ctx, kubeconfig, clusterName, namespace)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KubeconfigSecretAvailable indicates an expected call of KubeconfigSecretAvailable.
func (mr *MockKubernetesClientMockRecorder) KubeconfigSecretAvailable(ctx, kubeconfig, clusterName, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KubeconfigSecretAvailable", reflect.TypeOf((*MockKubernetesClient)(nil).KubeconfigSecretAvailable), ctx, kubeconfig, clusterName, namespace)
}

// ListObjects mocks base method.
func (m *MockKubernetesClient) ListObjects(ctx context.Context, resourceType, namespace, kubeconfig string, list kubernetes.ObjectList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, resourceType, namespace, kubeconfig, list)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockKubernetesClientMockRecorder) ListObjects(ctx, resourceType, namespace, kubeconfig, list any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockKubernetesClient)(nil).ListObjects), ctx, resourceType, namespace, kubeconfig, list)
}

// PauseCAPICluster mocks base method.
func (m *MockKubernetesClient) PauseCAPICluster(ctx context.Context, arg1, kubeconfig string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseCAPICluster", ctx, arg1, kubeconfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseCAPICluster indicates an expected call of PauseCAPICluster.
func (mr *MockKubernetesClientMockRecorder) PauseCAPICluster(ctx, arg1, kubeconfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseCAPICluster", reflect.TypeOf((*MockKubernetesClient)(nil).PauseCAPICluster), ctx, arg1, kubeconfig)
}

// RemoveAnnotationInNamespace mocks base method.
func (m *MockKubernetesClient) RemoveAnnotationInNamespace(ctx context.Context, resourceType, objectName, key string, arg4 *types.Cluster, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAnnotationInNamespace", ctx, resourceType, objectName, key, arg4, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAnnotationInNamespace indicates an expected call of RemoveAnnotationInNamespace.
func (mr *MockKubernetesClientMockRecorder) RemoveAnnotationInNamespace(ctx, resourceType, objectName, key, arg4, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAnnotationInNamespace", reflect.TypeOf((*MockKubernetesClient)(nil).RemoveAnnotationInNamespace), ctx, resourceType, objectName, key, arg4, namespace)
}

// ResumeCAPICluster mocks base method.
func (m *MockKubernetesClient) ResumeCAPICluster(ctx context.Context, arg1, kubeconfig string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeCAPICluster", ctx, arg1, kubeconfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumeCAPICluster indicates an expected call of ResumeCAPICluster.
func (mr *MockKubernetesClientMockRecorder) ResumeCAPICluster(ctx, arg1, kubeconfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeCAPICluster", reflect.TypeOf((*MockKubernetesClient)(nil).ResumeCAPICluster), ctx, arg1, kubeconfig)
}

// SaveLog mocks base method.
func (m *MockKubernetesClient) SaveLog(ctx context.Context, arg1 *types.Cluster, deployment *types.Deployment, fileName string, writer filewriter.FileWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLog", ctx, arg1, deployment, fileName, writer)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveLog indicates an expected call of SaveLog.
func (mr *MockKubernetesClientMockRecorder) SaveLog(ctx, arg1, deployment, fileName, writer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLog", reflect.TypeOf((*MockKubernetesClient)(nil).SaveLog), ctx, arg1, deployment, fileName, writer)
}

// SetEksaControllerEnvVar mocks base method.
func (m *MockKubernetesClient) SetEksaControllerEnvVar(ctx context.Context, envVar, envVarVal, kubeconfig string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEksaControllerEnvVar", ctx, envVar, envVarVal, kubeconfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEksaControllerEnvVar indicates an expected call of SetEksaControllerEnvVar.
func (mr *MockKubernetesClientMockRecorder) SetEksaControllerEnvVar(ctx, envVar, envVarVal, kubeconfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEksaControllerEnvVar", reflect.TypeOf((*MockKubernetesClient)(nil).SetEksaControllerEnvVar), ctx, envVar, envVarVal, kubeconfig)
}

// UpdateAnnotationInNamespace mocks base method.
func (m *MockKubernetesClient) UpdateAnnotationInNamespace(ctx context.Context, resourceType, objectName string, annotations map[string]string, arg4 *types.Cluster, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAnnotationInNamespace", ctx, resourceType, objectName, annotations, arg4, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAnnotationInNamespace indicates an expected call of UpdateAnnotationInNamespace.
func (mr *MockKubernetesClientMockRecorder) UpdateAnnotationInNamespace(ctx, resourceType, objectName, annotations, arg4, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAnnotationInNamespace", reflect.TypeOf((*MockKubernetesClient)(nil).UpdateAnnotationInNamespace), ctx, resourceType, objectName, annotations, arg4, namespace)
}

// UpdateEnvironmentVariablesInNamespace mocks base method.
func (m *MockKubernetesClient) UpdateEnvironmentVariablesInNamespace(ctx context.Context, resourceType, resourceName string, envMap map[string]string, arg4 *types.Cluster, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEnvironmentVariablesInNamespace", ctx, resourceType, resourceName, envMap, arg4, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEnvironmentVariablesInNamespace indicates an expected call of UpdateEnvironmentVariablesInNamespace.
func (mr *MockKubernetesClientMockRecorder) UpdateEnvironmentVariablesInNamespace(ctx, resourceType, resourceName, envMap, arg4, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEnvironmentVariablesInNamespace", reflect.TypeOf((*MockKubernetesClient)(nil).UpdateEnvironmentVariablesInNamespace), ctx, resourceType, resourceName, envMap, arg4, namespace)
}

// ValidateControlPlaneNodes mocks base method.
func (m *MockKubernetesClient) ValidateControlPlaneNodes(ctx context.Context, arg1 *types.Cluster, clusterName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateControlPlaneNodes", ctx, arg1, clusterName)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateControlPlaneNodes indicates an expected call of ValidateControlPlaneNodes.
func (mr *MockKubernetesClientMockRecorder) ValidateControlPlaneNodes(ctx, arg1, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateControlPlaneNodes", reflect.TypeOf((*MockKubernetesClient)(nil).ValidateControlPlaneNodes), ctx, arg1, clusterName)
}

// ValidateWorkerNodes mocks base method.
func (m *MockKubernetesClient) ValidateWorkerNodes(ctx context.Context, clusterName, kubeconfigFile string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateWorkerNodes", ctx, clusterName, kubeconfigFile)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateWorkerNodes indicates an expected call of ValidateWorkerNodes.
func (mr *MockKubernetesClientMockRecorder) ValidateWorkerNodes(ctx, clusterName, kubeconfigFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateWorkerNodes", reflect.TypeOf((*MockKubernetesClient)(nil).ValidateWorkerNodes), ctx, clusterName, kubeconfigFile)
}

// WaitForClusterReady mocks base method.
func (m *MockKubernetesClient) WaitForClusterReady(ctx context.Context, arg1 *types.Cluster, timeout, clusterName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForClusterReady", ctx, arg1, timeout, clusterName)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForClusterReady indicates an expected call of WaitForClusterReady.
func (mr *MockKubernetesClientMockRecorder) WaitForClusterReady(ctx, arg1, timeout, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForClusterReady", reflect.TypeOf((*MockKubernetesClient)(nil).WaitForClusterReady), ctx, arg1, timeout, clusterName)
}

// WaitForControlPlaneReady mocks base method.
func (m *MockKubernetesClient) WaitForControlPlaneReady(ctx context.Context, arg1 *types.Cluster, timeout, newClusterName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForControlPlaneReady", ctx, arg1, timeout, newClusterName)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForControlPlaneReady indicates an expected call of WaitForControlPlaneReady.
func (mr *MockKubernetesClientMockRecorder) WaitForControlPlaneReady(ctx, arg1, timeout, newClusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForControlPlaneReady", reflect.TypeOf((*MockKubernetesClient)(nil).WaitForControlPlaneReady), ctx, arg1, timeout, newClusterName)
}

// WaitForDeployment mocks base method.
func (m *MockKubernetesClient) WaitForDeployment(ctx context.Context, arg1 *types.Cluster, timeout, condition, target, namespace string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForDeployment", ctx, arg1, timeout, condition, target, namespace)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForDeployment indicates an expected call of WaitForDeployment.
func (mr *MockKubernetesClientMockRecorder) WaitForDeployment(ctx, arg1, timeout, condition, target, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForDeployment", reflect.TypeOf((*MockKubernetesClient)(nil).WaitForDeployment), ctx, arg1, timeout, condition, target, namespace)
}

// MockClientFactory is a mock of ClientFactory interface.
type MockClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockClientFactoryMockRecorder
	isgomock struct{}
}

// MockClientFactoryMockRecorder is the mock recorder for MockClientFactory.
type MockClientFactoryMockRecorder struct {
	mock *MockClientFactory
}

// NewMockClientFactory creates a new mock instance.
func NewMockClientFactory(ctrl *gomock.Controller) *MockClientFactory {
	mock := &MockClientFactory{ctrl: ctrl}
	mock.recorder = &MockClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientFactory) EXPECT() *MockClientFactoryMockRecorder {
	return m.recorder
}

// BuildClientFromKubeconfig mocks base method.
func (m *MockClientFactory) BuildClientFromKubeconfig(kubeconfigPath string) (kubernetes.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildClientFromKubeconfig", kubeconfigPath)
	ret0, _ := ret[0].(kubernetes.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildClientFromKubeconfig indicates an expected call of BuildClientFromKubeconfig.
func (mr *MockClientFactoryMockRecorder) BuildClientFromKubeconfig(kubeconfigPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildClientFromKubeconfig", reflect.TypeOf((*MockClientFactory)(nil).BuildClientFromKubeconfig), kubeconfigPath)
}

// MockClusterApplier is a mock of ClusterApplier interface.
type MockClusterApplier struct {
	ctrl     *gomock.Controller
	recorder *MockClusterApplierMockRecorder
	isgomock struct{}
}

// MockClusterApplierMockRecorder is the mock recorder for MockClusterApplier.
type MockClusterApplierMockRecorder struct {
	mock *MockClusterApplier
}

// NewMockClusterApplier creates a new mock instance.
func NewMockClusterApplier(ctrl *gomock.Controller) *MockClusterApplier {
	mock := &MockClusterApplier{ctrl: ctrl}
	mock.recorder = &MockClusterApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterApplier) EXPECT() *MockClusterApplierMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockClusterApplier) Run(ctx context.Context, spec *cluster.Spec, managementCluster types.Cluster) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, spec, managementCluster)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockClusterApplierMockRecorder) Run(ctx, spec, managementCluster any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockClusterApplier)(nil).Run), ctx, spec, managementCluster)
}

// MockCAPIClient is a mock of CAPIClient interface.
type MockCAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockCAPIClientMockRecorder
	isgomock struct{}
}

// MockCAPIClientMockRecorder is the mock recorder for MockCAPIClient.
type MockCAPIClientMockRecorder struct {
	mock *MockCAPIClient
}

// NewMockCAPIClient creates a new mock instance.
func NewMockCAPIClient(ctrl *gomock.Controller) *MockCAPIClient {
	mock := &MockCAPIClient{ctrl: ctrl}
	mock.recorder = &MockCAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCAPIClient) EXPECT() *MockCAPIClientMockRecorder {
	return m.recorder
}

// BackupManagement mocks base method.
func (m *MockCAPIClient) BackupManagement(ctx context.Context, arg1 *types.Cluster, managementStatePath, clusterName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackupManagement", ctx, arg1, managementStatePath, clusterName)
	ret0, _ := ret[0].(error)
	return ret0
}

// BackupManagement indicates an expected call of BackupManagement.
func (mr *MockCAPIClientMockRecorder) BackupManagement(ctx, arg1, managementStatePath, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackupManagement", reflect.TypeOf((*MockCAPIClient)(nil).BackupManagement), ctx, arg1, managementStatePath, clusterName)
}

// GetWorkloadKubeconfig mocks base method.
func (m *MockCAPIClient) GetWorkloadKubeconfig(ctx context.Context, clusterName string, arg2 *types.Cluster) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkloadKubeconfig", ctx, clusterName, arg2)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkloadKubeconfig indicates an expected call of GetWorkloadKubeconfig.
func (mr *MockCAPIClientMockRecorder) GetWorkloadKubeconfig(ctx, clusterName, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkloadKubeconfig", reflect.TypeOf((*MockCAPIClient)(nil).GetWorkloadKubeconfig), ctx, clusterName, arg2)
}

// InitInfrastructure mocks base method.
func (m *MockCAPIClient) InitInfrastructure(ctx context.Context, managementComponents *cluster.ManagementComponents, clusterSpec *cluster.Spec, arg3 *types.Cluster, provider providers.Provider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitInfrastructure", ctx, managementComponents, clusterSpec, arg3, provider)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitInfrastructure indicates an expected call of InitInfrastructure.
func (mr *MockCAPIClientMockRecorder) InitInfrastructure(ctx, managementComponents, clusterSpec, arg3, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitInfrastructure", reflect.TypeOf((*MockCAPIClient)(nil).InitInfrastructure), ctx, managementComponents, clusterSpec, arg3, provider)
}

// MoveManagement mocks base method.
func (m *MockCAPIClient) MoveManagement(ctx context.Context, from, target *types.Cluster, clusterName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveManagement", ctx, from, target, clusterName)
	ret0, _ := ret[0].(error)
	return ret0
}

// MoveManagement indicates an expected call of MoveManagement.
func (mr *MockCAPIClientMockRecorder) MoveManagement(ctx, from, target, clusterName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveManagement", reflect.TypeOf((*MockCAPIClient)(nil).MoveManagement), ctx, from, target, clusterName)
}
