# permissions for end users to edit cloudstackmachineconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudstackmachineconfig-editor-role
rules:
- apiGroups:
  - anywhere.eks.amazonaws.com
  resources:
  - cloudstackmachineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - anywhere.eks.amazonaws.com
  resources:
  - cloudstackmachineconfigs/status
  verbs:
  - get
