# permissions for end users to edit cloudstackdeploymentconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudstackdeploymentconfig-editor-role
rules:
- apiGroups:
  - anywhere.eks.amazonaws.com
  resources:
  - cloudstackdeploymentconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - anywhere.eks.amazonaws.com
  resources:
  - cloudstackdeploymentconfigs/status
  verbs:
  - get
