apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default

patchesStrategicMerge:
- manager_gates_patch.yaml

images:
- name: controller
  newName: cluster-controller
  newTag: latest
