// Code generated by smithy-go-codegen DO NOT EDIT.

package types

import (
	"fmt"
	smithy "github.com/aws/smithy-go"
)

type DependencyException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *DependencyException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *DependencyException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *DependencyException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "DependencyException"
	}
	return *e.ErrorCodeOverride
}
func (e *DependencyException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type HardwarePlatformNotRecognizedException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *HardwarePlatformNotRecognizedException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *HardwarePlatformNotRecognizedException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *HardwarePlatformNotRecognizedException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "HardwarePlatformNotRecognizedException"
	}
	return *e.ErrorCodeOverride
}
func (e *HardwarePlatformNotRecognizedException) ErrorFault() smithy.ErrorFault {
	return smithy.FaultClient
}

type IncorrectDeviceManifestException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *IncorrectDeviceManifestException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *IncorrectDeviceManifestException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *IncorrectDeviceManifestException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "IncorrectDeviceManifestException"
	}
	return *e.ErrorCodeOverride
}
func (e *IncorrectDeviceManifestException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type IncorrectDeviceStateException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *IncorrectDeviceStateException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *IncorrectDeviceStateException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *IncorrectDeviceStateException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "IncorrectDeviceStateException"
	}
	return *e.ErrorCodeOverride
}
func (e *IncorrectDeviceStateException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type IncorrectDeviceUpdateStateException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *IncorrectDeviceUpdateStateException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *IncorrectDeviceUpdateStateException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *IncorrectDeviceUpdateStateException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "IncorrectDeviceUpdateStateException"
	}
	return *e.ErrorCodeOverride
}
func (e *IncorrectDeviceUpdateStateException) ErrorFault() smithy.ErrorFault {
	return smithy.FaultClient
}

type InternalFailureException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *InternalFailureException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *InternalFailureException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *InternalFailureException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "InternalFailureException"
	}
	return *e.ErrorCodeOverride
}
func (e *InternalFailureException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type InvalidPaginationTokenException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *InvalidPaginationTokenException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *InvalidPaginationTokenException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *InvalidPaginationTokenException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "InvalidPaginationTokenException"
	}
	return *e.ErrorCodeOverride
}
func (e *InvalidPaginationTokenException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type InvalidParameterCombinationException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *InvalidParameterCombinationException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *InvalidParameterCombinationException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *InvalidParameterCombinationException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "InvalidParameterCombinationException"
	}
	return *e.ErrorCodeOverride
}
func (e *InvalidParameterCombinationException) ErrorFault() smithy.ErrorFault {
	return smithy.FaultClient
}

type InvalidParameterValueException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *InvalidParameterValueException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *InvalidParameterValueException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *InvalidParameterValueException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "InvalidParameterValueException"
	}
	return *e.ErrorCodeOverride
}
func (e *InvalidParameterValueException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type InvalidRequestException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *InvalidRequestException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *InvalidRequestException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *InvalidRequestException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "InvalidRequestException"
	}
	return *e.ErrorCodeOverride
}
func (e *InvalidRequestException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type MacAddressAlreadyInUseException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *MacAddressAlreadyInUseException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *MacAddressAlreadyInUseException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *MacAddressAlreadyInUseException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "MacAddressAlreadyInUseException"
	}
	return *e.ErrorCodeOverride
}
func (e *MacAddressAlreadyInUseException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type MaxDirectNetworkExceededException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *MaxDirectNetworkExceededException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *MaxDirectNetworkExceededException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *MaxDirectNetworkExceededException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "MaxDirectNetworkExceededException"
	}
	return *e.ErrorCodeOverride
}
func (e *MaxDirectNetworkExceededException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type MaxDirectNetworkOnInstanceException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *MaxDirectNetworkOnInstanceException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *MaxDirectNetworkOnInstanceException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *MaxDirectNetworkOnInstanceException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "MaxDirectNetworkOnInstanceException"
	}
	return *e.ErrorCodeOverride
}
func (e *MaxDirectNetworkOnInstanceException) ErrorFault() smithy.ErrorFault {
	return smithy.FaultClient
}

type MissingParameterException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *MissingParameterException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *MissingParameterException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *MissingParameterException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "MissingParameterException"
	}
	return *e.ErrorCodeOverride
}
func (e *MissingParameterException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type NoCloudConnectionException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *NoCloudConnectionException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *NoCloudConnectionException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *NoCloudConnectionException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "NoCloudConnectionException"
	}
	return *e.ErrorCodeOverride
}
func (e *NoCloudConnectionException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type NoDirectNetworkSupportException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *NoDirectNetworkSupportException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *NoDirectNetworkSupportException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *NoDirectNetworkSupportException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "NoDirectNetworkSupportException"
	}
	return *e.ErrorCodeOverride
}
func (e *NoDirectNetworkSupportException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type PciDeviceAlreadyAttachedException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *PciDeviceAlreadyAttachedException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *PciDeviceAlreadyAttachedException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *PciDeviceAlreadyAttachedException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "PciDeviceAlreadyAttachedException"
	}
	return *e.ErrorCodeOverride
}
func (e *PciDeviceAlreadyAttachedException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type PciDeviceMissingDataException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *PciDeviceMissingDataException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *PciDeviceMissingDataException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *PciDeviceMissingDataException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "PciDeviceMissingDataException"
	}
	return *e.ErrorCodeOverride
}
func (e *PciDeviceMissingDataException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type PciDeviceNotFoundException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *PciDeviceNotFoundException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *PciDeviceNotFoundException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *PciDeviceNotFoundException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "PciDeviceNotFoundException"
	}
	return *e.ErrorCodeOverride
}
func (e *PciDeviceNotFoundException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type PublicIpAlreadyAssociatedException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *PublicIpAlreadyAssociatedException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *PublicIpAlreadyAssociatedException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *PublicIpAlreadyAssociatedException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "PublicIpAlreadyAssociatedException"
	}
	return *e.ErrorCodeOverride
}
func (e *PublicIpAlreadyAssociatedException) ErrorFault() smithy.ErrorFault {
	return smithy.FaultClient
}

type ResourceNotFoundException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *ResourceNotFoundException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *ResourceNotFoundException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *ResourceNotFoundException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "ResourceNotFoundException"
	}
	return *e.ErrorCodeOverride
}
func (e *ResourceNotFoundException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type ServiceAlreadyStartedException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *ServiceAlreadyStartedException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *ServiceAlreadyStartedException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *ServiceAlreadyStartedException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "ServiceAlreadyStartedException"
	}
	return *e.ErrorCodeOverride
}
func (e *ServiceAlreadyStartedException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type TimeServiceSettingPersistenceException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *TimeServiceSettingPersistenceException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *TimeServiceSettingPersistenceException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *TimeServiceSettingPersistenceException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "TimeServiceSettingPersistenceException"
	}
	return *e.ErrorCodeOverride
}
func (e *TimeServiceSettingPersistenceException) ErrorFault() smithy.ErrorFault {
	return smithy.FaultClient
}

type TimeServiceUnavailableException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *TimeServiceUnavailableException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *TimeServiceUnavailableException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *TimeServiceUnavailableException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "TimeServiceUnavailableException"
	}
	return *e.ErrorCodeOverride
}
func (e *TimeServiceUnavailableException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type UnsupportedFeatureException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *UnsupportedFeatureException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *UnsupportedFeatureException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *UnsupportedFeatureException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "UnsupportedFeatureException"
	}
	return *e.ErrorCodeOverride
}
func (e *UnsupportedFeatureException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }

type UnsupportedOperationException struct {
	Message *string

	ErrorCodeOverride *string

	noSmithyDocumentSerde
}

func (e *UnsupportedOperationException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCode(), e.ErrorMessage())
}
func (e *UnsupportedOperationException) ErrorMessage() string {
	if e.Message == nil {
		return ""
	}
	return *e.Message
}
func (e *UnsupportedOperationException) ErrorCode() string {
	if e == nil || e.ErrorCodeOverride == nil {
		return "UnsupportedOperationException"
	}
	return *e.ErrorCodeOverride
}
func (e *UnsupportedOperationException) ErrorFault() smithy.ErrorFault { return smithy.FaultClient }
