apiVersion: v1
kind: Secret
metadata:
  name: {{.vsphereCredentialsName}}
  namespace: {{.eksaSystemNamespace}}
type: kubernetes.io/basic-auth
stringData:
  username: "{{.vsphereUsername}}"
  password: "{{.vspherePassword}}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.eksaLicenseName}}
  namespace: {{.eksaSystemNamespace}}
stringData:
  license: "{{.eksaLicense}}"
type: Opaque
---
