apiVersion: v1
kind: Secret
metadata:
  name: {{.vsphereCredentialsName}}
  namespace: {{.eksaSystemNamespace}}
type: kubernetes.io/basic-auth
data:
  username: {{.vsphereUsername | b64enc}}
  password: {{.vspherePassword | b64enc}}
  usernameCP: "{{.eksaCloudProviderUsername | b64enc}}"
  passwordCP: "{{.eksaCloudProviderPassword | b64enc}}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.eksaLicenseName}}
  namespace: {{.eksaSystemNamespace}}
stringData:
  license: "{{.eksaLicense}}"
type: Opaque
---
