apiVersion: v1
kind: Secret
metadata:
  name: csi-vsphere-config
  namespace: kube-system
stringData:
  csi-vsphere.conf: |+
    [Global]
    cluster-id = "default/{{.clusterName}}"
    thumbprint = "{{.thumbprint}}"

    [VirtualCenter "{{.vsphereServer}}"]
    user = "{{.vsphereUsername}}"
    password = "{{.vspherePassword}}"
    datacenters = "{{.vsphereDatacenter}}"
    insecure-flag = "{{.insecure}}"

    [Network]
    public-network = "{{.vsphereNetwork}}"

type: Opaque
---
apiVersion: v1
kind: Namespace
metadata:
  name: eksa-system
---
apiVersion: v1
kind: Secret
metadata:
  name: eksa-license
  namespace: eksa-system
stringData:
  license: "{{.eksaLicense}}"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: vsphere-credentials
  namespace: eksa-system
type: kubernetes.io/basic-auth
stringData:
  username: "{{.vsphereUsername}}"
  password: "{{.vspherePassword}}"