// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/providers/nutanix/client.go

// Package nutanix is a generated GoMock package.
package nutanix

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v3 "github.com/nutanix-cloud-native/prism-go-client/v3"
)

// Mockv3Client is a mock of v3Client interface.
type Mockv3Client struct {
	ctrl     *gomock.Controller
	recorder *Mockv3ClientMockRecorder
}

// Mockv3ClientMockRecorder is the mock recorder for Mockv3Client.
type Mockv3ClientMockRecorder struct {
	mock *Mockv3Client
}

// NewMockv3Client creates a new mock instance.
func NewMockv3Client(ctrl *gomock.Controller) *Mockv3Client {
	mock := &Mockv3Client{ctrl: ctrl}
	mock.recorder = &Mockv3ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockv3Client) EXPECT() *Mockv3ClientMockRecorder {
	return m.recorder
}

// GetCluster mocks base method.
func (m *Mockv3Client) GetCluster(ctx context.Context, uuid string) (*v3.ClusterIntentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCluster", ctx, uuid)
	ret0, _ := ret[0].(*v3.ClusterIntentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCluster indicates an expected call of GetCluster.
func (mr *Mockv3ClientMockRecorder) GetCluster(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCluster", reflect.TypeOf((*Mockv3Client)(nil).GetCluster), ctx, uuid)
}

// GetImage mocks base method.
func (m *Mockv3Client) GetImage(ctx context.Context, uuid string) (*v3.ImageIntentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", ctx, uuid)
	ret0, _ := ret[0].(*v3.ImageIntentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *Mockv3ClientMockRecorder) GetImage(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*Mockv3Client)(nil).GetImage), ctx, uuid)
}

// GetSubnet mocks base method.
func (m *Mockv3Client) GetSubnet(ctx context.Context, uuid string) (*v3.SubnetIntentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnet", ctx, uuid)
	ret0, _ := ret[0].(*v3.SubnetIntentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnet indicates an expected call of GetSubnet.
func (mr *Mockv3ClientMockRecorder) GetSubnet(ctx, uuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnet", reflect.TypeOf((*Mockv3Client)(nil).GetSubnet), ctx, uuid)
}

// ListCluster mocks base method.
func (m *Mockv3Client) ListCluster(ctx context.Context, getEntitiesRequest *v3.DSMetadata) (*v3.ClusterListIntentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCluster", ctx, getEntitiesRequest)
	ret0, _ := ret[0].(*v3.ClusterListIntentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCluster indicates an expected call of ListCluster.
func (mr *Mockv3ClientMockRecorder) ListCluster(ctx, getEntitiesRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCluster", reflect.TypeOf((*Mockv3Client)(nil).ListCluster), ctx, getEntitiesRequest)
}

// ListImage mocks base method.
func (m *Mockv3Client) ListImage(ctx context.Context, getEntitiesRequest *v3.DSMetadata) (*v3.ImageListIntentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListImage", ctx, getEntitiesRequest)
	ret0, _ := ret[0].(*v3.ImageListIntentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListImage indicates an expected call of ListImage.
func (mr *Mockv3ClientMockRecorder) ListImage(ctx, getEntitiesRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImage", reflect.TypeOf((*Mockv3Client)(nil).ListImage), ctx, getEntitiesRequest)
}

// ListSubnet mocks base method.
func (m *Mockv3Client) ListSubnet(ctx context.Context, getEntitiesRequest *v3.DSMetadata) (*v3.SubnetListIntentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubnet", ctx, getEntitiesRequest)
	ret0, _ := ret[0].(*v3.SubnetListIntentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubnet indicates an expected call of ListSubnet.
func (mr *Mockv3ClientMockRecorder) ListSubnet(ctx, getEntitiesRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubnet", reflect.TypeOf((*Mockv3Client)(nil).ListSubnet), ctx, getEntitiesRequest)
}
