apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/managed-by: tilt
    control-plane: eksa-controller-manager
  name: eksa-controller-manager
  namespace: eksa-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: eksa-controller-manager
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: tilt
        control-plane: eksa-controller-manager
        tilt.dev/pod-template-hash: 5b1c91dd6f36e5bc7c6b
    spec:
      containers:
        - args:
            - "--health-probe-bind-address=:8081"
            - "--metrics-bind-address=127.0.0.1:8080"
            - "--leader-elect"
          command:
            - "/tilt-restart-wrapper"
            - "--watch_file=/tmp/.restart-proc"
            - sh
            - "-c"
            - "/manager"
          image: public.ecr.aws/j9l9l0k3/cluster-controller:tilt-083440eb74f01f09
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: "/healthz"
              port: healthz
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - containerPort: 8081
              name: healthz
              protocol: TCP
          readinessProbe:
            httpGet:
              path: "/readyz"
              port: healthz
          resources: {}
          volumeMounts:
            - mountPath: "/tmp/k8s-webhook-server/serving-certs"
              name: cert
              readOnly: true
        - args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:8080/"
            - "--logtostderr=true"
            - "--v=10"
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
          imagePullPolicy: IfNotPresent
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
          resources: {}
      securityContext:
        fsGroup: 1000
      serviceAccountName: eksa-controller-manager
      terminationGracePeriodSeconds: 10
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
