[plugins."io.containerd.grpc.v1.cri".registry.mirrors]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."public.ecr.aws"]
    endpoint = ["https://{{.registryMirrorAddress}}"]
{{- if .registryCACert }}
    [plugins."io.containerd.grpc.v1.cri".registry.configs."{{.registryMirrorAddress}}".tls]
    ca_file = "/etc/containerd/certs.d/{{.registryMirrorAddress}}/ca.crt"
{{- end }}