//go:build e2e
// +build e2e

package e2e

import (
	"github.com/aws/eks-anywhere/test/framework"
)

// runVSphereAirgapConfigFlow run airgap deployment but allow bootstrap cluster to access local peers.
func runVSphereAirgapConfigFlow(test *framework.ClusterE2ETest, localCIDRs string) {
	test.GenerateClusterConfig()
	test.DownloadArtifacts()
	test.ImportImages()
	test.ExtractDownloadedArtifacts()
	test.AirgapDockerContainers(localCIDRs)
	test.CreateAirgappedUser(localCIDRs)
	test.CreateCluster(
		framework.WithSudo("airgap"),
		framework.WithBundlesOverride("./eks-anywhere-downloads/bundle-release.yaml"), // generated by ExtractDownloadArtifacts
	)
	test.DeleteCluster()
}
